In [1]:
#using Pkg
#Pkg.add("PrettyTables")
using JSON
using Random
using Distributions
using MySQL
using DotEnv
using DataFrames
using PrettyTables
cfg = DotEnv.config(path="../.env")
const DB = DBInterface
include("/home/peters/code/mapinator/estimation/functions.jl")
YEAR_INTERVAL = 2003:2023  # change this to select the years of data to include in the estimation
NUM = 5 # variable set it here
NUMSINKS = 6 #4 sinks are assumed in some of the code
sinks = ["Other Academic","Government","Private Sector","Teaching Universities","Postdoc", "Sessionals","Column Totals"]
function name_to_oid(name, institution_mapping)
    ## returns an institution_id
    for (key, value) in institution_mapping
        if value == name
            return key
        end
    end
    return "not found"
end

name_to_oid (generic function with 1 method)

bucket_extract

In [2]:
 academic_builder, sink_builder, academic, acd_sink, gov_sink, pri_sink, tch_sink, postdoc, lecturer, institution_mapping = functions.process_data(YEAR_INTERVAL);

Debug: 14876 returned from api
Debug: 7273 academic placements
Debug: 7603 sinks
Debug: 14876 in all

In [3]:
println(length(academic_builder), " total assistant professor outcomes")
    println(length(sink_builder), " other outcomes")
    sample_size = length(academic_builder)+length(sink_builder)
    println(sample_size, " total outcomes")
println(length(acd_sink), " Other academic institutions")
println(length(gov_sink), " Government institutions")
println(length(pri_sink), " Private Sector institutions")
println(length(tch_sink), " Teaching institutions")
println(length(postdoc), " Institutions hiring postdocs")
println(length(lecturer), " Institutions hiring sessionals")

7273 total assistant professor outcomes
7603 other outcomes
14876 total outcomes
553 Other academic institutions
155 Government institutions
195 Private Sector institutions
627 Teaching institutions
514 Institutions hiring postdocs
366 Institutions hiring sessionals

In [4]:
institutions, out = functions.create_adjacency_matrix(academic_builder, sink_builder, academic,acd_sink, gov_sink, pri_sink, tch_sink, postdoc, lecturer);

In [ ]:
est_obj, est_alloc = functions.doit(out, collect(academic),collect(acd_sink), collect(gov_sink), collect(pri_sink), collect(tch_sink), collect(postdoc), collect(lecturer),institutions, NUM, NUMSINKS);

In [ ]:
est_mat, est_count = functions.bucket_extract(est_alloc, out, NUM, NUMSINKS)
M = est_mat

In [ ]:
t_table, t_allocation = functions.tiered_allocation(M, est_count, institutions, est_alloc, NUM, NUMSINKS);
t_table

In [ ]:
table_latex = functions.nice_table(t_table, NUM, NUMSINKS, sinks)
table_latex

In [ ]:
#for line in institution_mapping
#    println(line)
#end#

In [ ]:
d = DB.connect(MySQL.Connection,cfg["host"], cfg["user"], cfg["password"], db =cfg["database"], port = parse(Int64,cfg["port"]));
query = "select i.name,j.institution_id ,
SUM(CASE
  WHEN j.estimated_tier = 1 THEN count ELSE 0 END
) AS TIER1,
SUM(CASE
  WHEN j.estimated_tier = 2 THEN count ELSE 0 END
) AS TIER2,
SUM(CASE
  WHEN j.estimated_tier = 3 THEN count ELSE 0 END
) AS TIER3,
SUM(CASE
  WHEN j.estimated_tier = 4 THEN count ELSE 0 END
) AS TIER4,
SUM(CASE
  WHEN j.estimated_tier = 5 THEN count ELSE 0 END
) AS TIER5


from ftrecruiter.institutions i join
(select d.institution_id, d.estimated_tier, count(*) as count from bootstrap_data d left join bootstrap_trials t  
on t.trial_id=d.trial_id where t.number_of_tiers=?
group by institution_id, estimated_tier) j on i.institution_id=j.institution_id where j.institution_id=?
group by j.institution_id"
get_statement =  DB.prepare(d, query);

In [39]:
function get_confidence(tiers, institution_id, get_statement)
    m = DB.execute(get_statement, [tiers, institution_id]) |> DataFrame
    return m
    if nrow(m) > 0
        r = first(m)
        t = 0
        s = 0
        s+= r.TIER1
        s+= r.TIER2
        s+= r.TIER3
        s+= r.TIER4
        s+= r.TIER5
        est = [r.TIER1/s, r.TIER2/s, r.TIER3/s, r.TIER4/s, r.TIER5/s]
        return findmax(est)
    else return string(institution_id," ",tiers, "  not found")
    end
    
end

get_confidence (generic function with 1 method)

In [40]:
println(name_to_oid("Ohio State University", institution_mapping))
#println(get_confidence(NUM, name_to_oid("Unversity of British Columbia", institution_mapping), get_statement))
get_confidence(5, 465, get_statement)

465

0×7 DataFrame
 Row │ name     institution_id  TIER1  TIER2  TIER3  TIER4  TIER5
     │ String?  Int32?          Dec64  Dec64  Dec64  Dec64  Dec64
─────┴────────────────────────────────────────────────────────────

In [42]:
for j in 1:NUM
    println("********")
    println("Tier $j:")
    tier = Dict{}()
    for (i, type) in enumerate(t_allocation)
        if type == j
            
            #push!(tier, (institutions[i] => get_confidence(NUM, name_to_oid(institutions[i], institution_mapping), get_statement)))
            push!(tier, institutions[i] => 1)
            println(institutions[i])
            #println("  ", institutions[i], " Confidence: ", get_confidence(NUM, name_to_oid(institutions[i], institution_mapping), get_statement))
        end
    end
    #pretty_table(tier; header = ["University", "Confidence"])
    #pretty_table(tier; header = ["University", "Confidence"], backend=Val(:latex))
end

********
Tier 1:
University of Wisconsin, Madison
Stanford University
Duke University
University of Maryland
Northwestern University
London School of Economics and Political Science
Harvard University
Yale University
University of Michigan
Columbia University
Massachusetts Institute of Technology
New York University
Princeton University
University of Chicago
University of Pennsylvania
University of California, Berkeley
University of California Los Angeles (UCLA)
********
Tier 2:
Boston College
University of Warwick
National University of Singapore
Bocconi University
Ohio State University
University of Cambridge
University of Texas at Austin
Vanderbilt University
Erasmus University Rotterdam
Johns Hopkins University
University College London
University of Bonn
Arizona State University
University of Rochester
University of Virginia
Cornell University
University of British Columbia
Maastricht University
University of Washington
University of Oxford
Michigan State University
École d'Économie de Paris
Tilburg University
Texas A&M University, College Station
University of Nottingham
Stockholm School of Economics
University of Arizona
University of Minnesota, Twin Cities
Purdue University
Brown University
University of Mannheim
University of Toronto
European University Institute
University of Illinois at Urbana-Champaign
Université Toulouse Capitole
Boston University
University of California, San Diego
University of Southern California
Washington State University
University of California, Davis
Universitat Pompeu Fabra
Washington University in St. Louis
Carnegie Mellon University
Pennsylvania State University
********
Tier 3:
Peking University
University of Leicester
London Business School
University of Zurich
Syracuse University
University of Copenhagen
Toronto Metropolitan University
Aix-Marseille Université
University of Nebraska, Lincoln
University of North Carolina, Chapel Hill
City University of London
University of Amsterdam
McGill University
Universíté de Montréal
Goethe-Universität Frankfurt am Main
University of Queensland
Hong Kong University of Science and Technology
University of Houston
Louisiana State University
University of Notre Dame
University of Georgia
Tsinghua University
University of Connecticut
Florida State University
University of Hawaiʻi at Mānoa
Università di Roma Tor Vergata
University of California, Santa Barbara
University of Oslo
Università di Bologna
Concordia University
Auburn University
Norwegian School of Economics (NHH)
Western University
Ecole Polytechnique (IP Paris)
Rutgers, The State University of New Jersey
Sciences Po
Queen Mary University of London
Instituto Tecnologico Autónomo de Mexico (ITAM)
Aarhus University
University of Calgary
Monash University
Oregon State University
Queen's University
University of Groningen
University of Oklahoma
University of California, Irvine
University of Oregon
Southern Methodist University
BI Norwegian Business School
Uppsala University
Shanghai University of Finance and Economics
University of Alabama
University of Melbourne
Texas Tech University
Seoul National University
University of Pittsburgh
Northeastern University
Ludwig-Maximilians-Universitat München (LMU) (University of Munich)
Oklahoma State University
Virginia Tech
American University
Universidad Carlos III de Madrid
University of Colorado, Boulder
University of Massachusetts, Amherst
Universidad de los Andes
Wuhan University
Australian National University
Lund University
Copenhagen Business School
University of Iowa
Clemson University
University of California, Riverside
Iowa State University
Stony Brook University (SUNY)
University of International Business and Economics
University of Florida
West Virginia University
University of New South Wales (UNSW), Sydney
Utrecht University
University of Essex
North Carolina State University
Kansas State University
University of Kansas
University of California, Santa Cruz
CEMFI
Katholieke Universiteit Leuven
McMaster University
University of Delaware
Temple University
Rice University
University of Gothenburg
Georgetown University
Vrije Universiteit Amsterdam
Simon Fraser University
George Mason University
The New School
Georgia Institute of Technology
ETH Zurich
Indiana University Bloomington
University of Glasgow
Singapore Management University
University of Missouri, Columbia
University of Lausanne
Binghamton University (SUNY)
University of Vienna
University of Manchester
Stockholm University
University of Alberta
Georgia State University
Xiamen University
Chinese University of Hong Kong
INSEAD
Tulane University
University of Illinois at Chicago
Emory University
Universitat Autònoma de Barcelona
George Washington University
********
Tier 4:
Indian Statistical Institute, Delhi
Eastern Kentucky University
Rutgers University, Newark
University of Cologne
Leiden University
University of Rhode Island
Ca' Foscari University Venice
University of St Andrews
Mississippi State University
City University of Hong Kong
Shiv Nadar University
Radboud University
University of Nevada, Las Vegas (UNLV)
Wayne State University
Université Laval
IE University
University of Bath
University of Sydney
Tel Aviv University
Deakin University
Charles University
University of Cincinnati
University of Sheffield
University of North Carolina, Charlotte
University of South Carolina
York University
Ball State University
Center for Research in Economics and Statistics (CREST)
Université du Québec à Montréal (UQAM)
Howard University
University of Leeds
ESMT Berlin
National Central University
CERGE-EI (Center for Economic Research and Graduate Education – Economics Institute)
City University of New York Graduate Center
Loughborough University
Sam Houston State University
Zhongnan University of Economics and Law
SOAS (School of Oriental and African Studies), University of London
University of Technology Sydney
University of Saskatchewan
Özyeğin University
Chr. Michelsen Institute (CMI)
Birkbeck College, University of London
Université Libre de Bruxelles
University of Strathclyde
University of Colorado, Denver
Aligarh Muslim University
University of Louisville
Fundação Getulio Vargas (FGV)
Université Paris-Dauphine
University of Wyoming
Dalhousie University
National Research University Higher School of Economics, St. Petersburg
HEC Paris
Université de Genève
Pontificia Universidad Católica de Chile
University of Konstanz
Lancaster University
Insper (Institute of Education and Research)
Korea University
LUISS Guido Carli
Wilfrid Laurier University
Colorado State University
Osaka University
University of Adelaide
Waseda University
National Research University Higher School of Economics, Moscow
University of Southampton
Universidad Complutense de Madrid
Università degli Studi di Verona
New York University Shanghai
Università della Svizzera Italiana
Lehigh University
University of Innsbruck
University of New Mexico
Ghent University
University of Southern Denmark
Universidade Nova de Lisboa
University of Utah
Pontifical Catholic University of Rio de Janeiro
Royal Holloway, University of London
University of Surrey
University of Exeter
Universitat de Barcelona
University of Victoria
University of North Carolina, Greensboro
Florida International University
University of Helsinki
East China Normal University
Collegio Carlo Alberto
Dongbei University of Finance and Economics
University of Birmingham
University of Mississippi
California State Polytechnic University, Pomona
University of Minho
Johannes Kepler University Linz
Baruch College, City University of New York
University of York
Colorado School of Mines
Technische Universität Berlin
Universidad de Navarra
Universidad del Rosario
University of Western Australia
Bentley University
University of Vaasa
University of Reading
University of North Texas
University of Texas at Arlington
Université Paris 1 Panthéon-Sorbonne
University of Miami
Sogang University
Università degli Studi di Firenze
University of Kent
Trinity College Dublin, University of Dublin
University of Edinburgh
Graduate Institute of International and Development Studies
Durham University
Freie Universität Berlin
California Institute of Technology (Caltech)
Aalto University
Bilkent University
University of Jena
University of Ottawa
Miami University
King's College London
Vienna Graduate School of Finance (VGSF)
University of Memphis
University of Hong Kong
Università degli Studi di Torino
University of South Florida
Clark University
Hunter College, CUNY
IMT School for Advanced Studies Lucca
Indira Gandhi Institute of Development Research (IGIDR)
Fudan University
University of Haifa
New York University Abu Dhabi
Vienna University of Economics and Business
Shandong University
Sciences Po Toulouse
University of Guelph
University of Bristol
University of Wisconsin, Milwaukee
Università Cattolica del Sacro Cuore
University of Nevada, Reno
Frankfurt School of Finance & Management
University of Central Florida
University of Tokyo
Athens University of Economics and Business
Claremont Graduate University
University of São Paulo
University of Texas at Dallas
Hong Kong Polytechnic University
ESSEC Business School
Eastern Mediterranean University
Università Degli Studi di Milano
Hong Kong Baptist University
Università degli Studi di Trento
Fordham University
Université catholique de Louvain
University of St. Gallen
Hanyang University
Università degli Studi di Pavia
Drexel University
University of Kentucky
University of Liverpool
Carleton University
Tufts University
Hebrew University of Jerusalem
New Mexico State University
İzmir University of Economics
Universitat de València
Sun Yat-Sen University
University of Waterloo
University of Göttingen
Brandeis University
Royal Melbourne Institute of Technology (RMIT)
East Carolina University
University of Bern
Koç University
University of Tsukuba
University of East Anglia
Manchester Metropolitan University
University of Manitoba
Barcelona School of Economics
Humboldt University Berlin
Imperial College London
Central European University
University of Auckland
University of Tennessee, Knoxville
University at Albany (SUNY)
University of Maine, Orono
University of Crete
University College Dublin
Nanyang Technological University
University of Sussex
Universidad de Alicante
Queens' University Belfast
State University of New York at Buffalo
Heidelberg University
University of New Hampshire
Indian Institute of Technology, Kanpur
University of Arkansas
Wageningen University
Delft University of Technology
Middle Tennessee State University
Queensland University of Technology
Sapienza Università di Roma
Cardiff University
New Economic School
SUNY Buffalo State
Utah State University
********
Tier 5:
Indian Institute of Technology, Indore
University of Jammu
Indiana Institute of Technology
Technische Universität Dresden
Université de Toulon
University of Dundee
University of Bergen
Università degli Studi di Napoli Federico II
University of Muenster
University of Waikato
Istanbul University
Universidad Rey Juan Carlos
Tarbiat Modares University
Kurukshetra University
KTH Royal Institute of Technology
EDHEC Business School
Institute of Technology Sligo
Ferdowsi University of Mashhad
Université de Picardie Jules Verne
Leipzig University
University of Galway
Universiteit Antwerpen
University of Carthage
ITMO University
University of Namur
Università degli Studi di Ferrara
École Normale Superieure de Lyon
Bharathidasan University
Université d'Orléans
Grenoble Ecole de Management
Corvinus University of Budapest
Massey University
University of Huddersfield
Université Clermont Auvergne
Chinese Academy of Sciences
Norges Artiske Universitet
University of Freiburg
Indian Institute of Management Bangalore
Indian Institute of Technology, Kharagpur
Tecnológico de Monterrey
Middle East Technical University - Northern Cyprus Campus
University of Sarajevo
University of Pretoria
University College Cork
Indian Institute of Technology, Madras
Quaid-i-Azam University
University of Cape Town
University of KwaZulu-Natal
Università degli Studi di Bergamo
University of Jyväskylä
Vysoká škola ekonomická v Praze
Institut national de recherche pour l'agriculture, l'alimentation et l'environnement (INRAE)
Budapest University of Technology and Economics
Meiji University
University of Alabama at Birmingham
Universidad de Zaragoza
University of Otago
ENSAE Paris Tech
Norwegian University of Science and Technology
Università di Pisa
University Putra Malaysia
Université Toulouse Jean Jaurès
Bournemouth University
Indian Statistical Institute, Kolkata
Universidad de Castilla-La Mancha
Università degli studi di Modena e Reggio Emilia
Universitat Rovira i Virgili
University of Lucknow
Ruhr Graduate School in Economics
Universiti Utara Malaysia
Universidad Pontificia Comillas
Bayero University, Kano
Manchester University
University of Algiers 3
University of Wollongong
Kingston University London
Federal University of Rio de Janeiro
University of Nairobi
University of Bradford
Bank of Finland
Union College
Institute for Advanced Study in Toulouse
Sharif University of Technology
University of Gloucestershire
Kiel University
Telecom ParisTech
Helwan University
Newcastle University
Stevens Institute of Technology
RAND Corporation
University of the Western Cape
Dublin Institute of Technology
University of Portsmouth
Universiti Kebangsaan Malaysia
International Centre for Education in Islamic Finance
Stellenbosch University
University of Botswana
University of Beira Interior
Technical University of Munich
Marietta College
Indian Institute of Science
ISM University of Management and Economics
University of Limerick
Walden University
Lomonosov Moscow State University (Московский государственный университет имени М. В. Ломоносова)
Gauhati University
University of Tirana
International Monetary Fund (IMF)
Université d'Evry Val-d'Essonne
Auckland University of Technology
University of Lisbon
Indiana University Purdue University Indianapolis (IUPUI)
Coventry University
Université Claude Bernard Lyon 1
Oxford Brookes University
Università degli Studi di Milano Biocca
Penn State Abington
Academy of Postgraduate Education (Академия последипломного образования)
Université de Montpellier
Technion
Rabindra Bharati University
University of the West of Scotland
Anglia Ruskin University
University of Iceland
Kyoto University
CY Cergy Paris Université
FUCAPE Business School
International Islamic University, Islamabad
Universitat Ramon Llull
Université Cheikh Anta Diop de Dakar
University of Hull
Suffolk University
Wuhan University of Technology
University of Tasmania
Southern Illinois University, Carbondale
Technical University of Denmark
ICFAI Foundation for Higher Education
Edith Cowan University
Aston University
University of Passau
Northern Illinois University
AgroParisTech
Aveiro University
Saint Petersburg University
Tohoku University
National University of Sciences and Technology (NUST)
Covenant University
Cairo University
Otto-von-Guericke University Magdeburg
Harbin Institute of Technology
Towson University
Drew University
Staffordshire University
Dublin City University
Università degli Studi di Palermo
Instituto Universitário de Lisboa, ISCTE-IUL
Federal University of Paraná
University of Southern Mississippi
Università degli Studi del Molise
Multimedia University
University of Fribourg
Pardee RAND Graduate School
University of Newcastle
Hanken School of Economics
University of South Alabama
International Islamic University Malaysia
Universidad Nacional Autónoma de México (UNAM)
Ss. Cyril and Methodius University in Skopje (Универзитет „Св. Кирил и Методиј“ во Скопје)
Univerzita Pardubice
University of Lucerne
University of Luxembourg
Halle Institute for Economic Research (IWH)
Stripe
Université de Lorraine
University of Hyderabad
Texas A&M International University
Université de Pau et des Pays de l'Adour
Macquarie University
Pan-Atlantic University
University of Stavanger
Katholische Universität Eichstätt-Ingolstadt
Swiss Tropical and Public Health Institute
Università degli Studi di Roma Tre
Universidad Politécnica de Madrid
Umeå University
Aristotle University of Thessaloniki
Kwara State University
Norwegian University of Life Sciences
Linnéuniversitetets
Politecnico di Torino
Universidad de Cantabria
Ecole des Hautes Etudes en Sciences Sociales (EHESS)
Université Paris 2 Panthéon-Assas
Università Carlo Cattaneo
Università degli Studi di Siena
Central Michigan University
Sultan Qaboos University
National Graduate Institute for Policy Studies (GRIPS), Japan
University of Malaya
Libera Università di Bolzano
Technological University Dublin
Bielefeld University
University of Fort Hare
Old Dominion University
Middle East Technical University
Griffith University
Université de Strasbourg
Korea Advanced Institute of Science and Technology (KAIST)
Thammasat University
Kangwon National University
Marmara University
Technische Universität Dortmund
K. N. Toosi University of Technology
Julius-Maximilians-Universität Würzburg
Heriot Watt University
University of the Aegean
University of Swansea
North-West University
Université de Tunis
Tallinn University of Technology
Zhejiang Gongshang University
Istanbul Bilgi University
Tampere University
Glasgow Caledonian University
Indian Institute of Management Indore
Leibniz Universität Hannover
Université de Bordeaux
SKEMA Business School
Technical University of Crete
Paderborn University
University of Johannesburg
St. Thomas University
University of Northern British Columbia
Université Paris 13
University of Massachusetts, Lowell
Universidad de Granada
Universiti Malaysia Perlis
Alexandria University
Università degli Studi di Macerata
Sari Agricultural Sciences and Natural Resources University
Instituto de Matemática Pura e Aplicada (IMPA)
Université Lumière Lyon 2
Universitat Jaume I
Università degli Studi "G. D’Annunzio" Chieti-Pescara
Obafemi Awolowo University
Banco de Portugal
Universidad de Salamanca
Kobe University
University of Bamenda
Southern Illinois University
National Institute of Development Administration
Philipps University Marburg
University of Warsaw
MINES ParisTech
Nelson Mandela University
Devi Ahilya Vishwavidyalaya, Indore
Jawaharlal Nehru University
Jaypee Institute of Information Technology
Universidad Anáhuac
Universitat Politecnica de Catalunya
Università degli Studi di Padova
Université Paris Nanterre
Université de Lille
University of Canterbury
Yildiz Technical University
University of Bedfordshire
ESCP Business School
University of Duisburg-Essen
Universidad de Valladolid
Université de Poitiers
Nnamdi Azikiwe University
University of Cyprus
University of Science and Technology in China
Brunel University London
Cochin University of Science and Technology
University of Basel
Justus-Liebig-Universität Gießen
Instituto Politécnico Nacional (IPN)
University of East London
Université Paris-Est Marne-la-Vallée
Università degli Studi di Genova
Università degli Studi dell'Insubria
Universidade Tecnológica Federal do Paraná
Università Politecnica delle Marche
Indian Institute of Technology, Delhi
Swedish University of Agricultural Sciences
Federal Reserve Bank of New York
Indian Institute of Management Kozhikode
Saint Mary's University (SMU)
University of Roehampton
Pakistan Institute of Development Economics
Sorbonne Université
Universiti Sains Malaysia
Hamburg University
Near East University
École Normale Supérieure Paris-Saclay
University of Mazandaran
Sant'Anna School of Advanced Studies
Università degli Studi di Messina
University of Sfax
RWTH Aachen University
Université Paris-Saclay
University of Massachusetts, Boston
University of Dschang
Illinois Institute of Technology
Pusan National University
Université de Technologie de Compiègne
University of New Orleans
Bond University
Jiwaji University
École Polytechnique Fédérale de Lausanne
University of Zagreb
Galatasaray University
Université Grenoble Alpes
Linköping University
Universidad Publica de Navarra
University of Missouri, Kansas City
Technische Universität Braunschweig
University of Turku