In [1]:
include("type_allocation_flexible.jl")

using Random, JSON

First we configure the settings:

In [2]:
Random.seed!(0)            # for reproducibility: ensures random results are the same on script restart
YEAR_INTERVAL = 2003:2025; # change this to select the years of data to include in the analysis

In this example, we want the most flexibility with the sinks, so we use the largest dataset:

In [3]:
to_from_by_year_api = SBM_flexible.fetch_data("https://support.econjobmarket.org/api/placement_data")

DataStructures.DefaultDict{Any, Any, UnionAll} with 23 entries:
  "2003" => Dict{Any, Any}("17827"=>Dict{String, Any}("to_shortname"=>"Economic…
  "2005" => Dict{Any, Any}("11382"=>Dict{String, Any}("to_shortname"=>"Economic…
  "2014" => Dict{Any, Any}("56926"=>Dict{String, Any}("to_shortname"=>"Business…
  "2018" => Dict{Any, Any}("37159"=>Dict{String, Any}("to_shortname"=>"Dallas o…
  "2020" => Dict{Any, Any}("45907"=>Dict{String, Any}("to_shortname"=>"Economic…
  "2010" => Dict{Any, Any}("5422"=>Dict{String, Any}("to_shortname"=>"Managemen…
  "2016" => Dict{Any, Any}("1886"=>Dict{String, Any}("to_shortname"=>"Cons Fina…
  "2019" => Dict{Any, Any}("43054"=>Dict{String, Any}("to_shortname"=>"Computer…
  "2004" => Dict{Any, Any}("24943"=>Dict{String, Any}("to_shortname"=>"Economic…
  "2007" => Dict{Any, Any}("24350"=>Dict{String, Any}("to_shortname"=>"Economic…
  "2023" => Dict{Any, Any}("57428"=>Dict{String, Any}("to_shortname"=>"Health P…
  "2017" => Dict{Any, Any}("27626"=>Dict{String, Any}("to_shortname"=>"Economic…
  "2022" => Dict{Any, Any}("53030"=>Dict{String, Any}("to_shortname"=>"Economic…
  "2021" => Dict{Any, Any}("51250"=>Dict{String, Any}("to_shortname"=>"Fondazio…
  "2006" => Dict{Any, Any}("41645"=>Dict{String, Any}("to_shortname"=>"Fed Rese…
  "2011" => Dict{Any, Any}("9123"=>Dict{String, Any}("to_shortname"=>"Econ, Sto…
  "2025" => Dict{Any, Any}("56703"=>Dict{String, Any}("to_shortname"=>"Strategy…
  "2015" => Dict{Any, Any}("24377"=>Dict{String, Any}("to_shortname"=>"Economic…
  "2012" => Dict{Any, Any}("21569"=>Dict{String, Any}("to_shortname"=>"Economic…
  "2013" => Dict{Any, Any}("16501"=>Dict{String, Any}("to_shortname"=>"Finance,…
  "2024" => Dict{Any, Any}("57394"=>Dict{String, Any}("to_shortname"=>"Manageme…
  "2008" => Dict{Any, Any}("3720"=>Dict{String, Any}("to_shortname"=>"Economics…
  "2009" => Dict{Any, Any}("1886"=>Dict{String, Any}("to_shortname"=>"Economics…

We can then sort the placements into academic and sinks, and collect some initial department labels:

In [4]:
academic, academic_to, academic_builder, rough_sink_builder, institution_mapping, reverse_mapping = SBM_flexible.get_builders(to_from_by_year_api, YEAR_INTERVAL);

We also need to retrieve the type allocation. We can either obtain this from a JSON file:

In [5]:
# tier_data = JSON.parsefile(".estimates/id_to_type_api.json")

or from the API, which is what we will use here:

In [6]:
tier_data = SBM_flexible.fetch_api("https://support.econjobmarket.org/api/academic_tiers")

839-element Vector{Any}:
 Dict{String, Any}("name" => "Harvard University", "institution_id" => 350, "type" => 1)
 Dict{String, Any}("name" => "COMSATS University Islamabad", "institution_id" => 1197, "type" => 5)
 Dict{String, Any}("name" => "Florida State University", "institution_id" => 324, "type" => 3)
 Dict{String, Any}("name" => "Thammasat University", "institution_id" => 3576, "type" => 5)
 Dict{String, Any}("name" => "Heinrich Heine University Dusseldorf", "institution_id" => 1258, "type" => 5)
 Dict{String, Any}("name" => "University of Portsmouth", "institution_id" => 1981, "type" => 5)
 Dict{String, Any}("name" => "Deakin University", "institution_id" => 1818, "type" => 4)
 Dict{String, Any}("name" => "Université de Picardie Jules Verne", "institution_id" => 3591, "type" => 5)
 Dict{String, Any}("name" => "Jinan University", "institution_id" => 902, "type" => 4)
 Dict{String, Any}("name" => "University of Iowa", "institution_id" => 1542, "type" => 3)
 Dict{String, Any}("name" => "IMT School for Advanced Studies Lucca", "institution_id" => 39, "type" => 4)
 Dict{String, Any}("name" => "University of Gothenburg", "institution_id" => 894, "type" => 4)
 Dict{String, Any}("name" => "Tarbiat Modares University", "institution_id" => 4119, "type" => 5)
 ⋮
 Dict{String, Any}("name" => "WHU - Otto Beisheim School of Management", "institution_id" => 1134, "type" => 5)
 Dict{String, Any}("name" => "University of Crete", "institution_id" => 4121, "type" => 5)
 Dict{String, Any}("name" => "Claremont Graduate University", "institution_id" => 1292, "type" => 4)
 Dict{String, Any}("name" => "Brunel University London", "institution_id" => 1732, "type" => 5)
 Dict{String, Any}("name" => "Fordham University", "institution_id" => 1494, "type" => 4)
 Dict{String, Any}("name" => "Özyeğin University", "institution_id" => 330, "type" => 4)
 Dict{String, Any}("name" => "SKEMA Business School", "institution_id" => 384, "type" => 5)
 Dict{String, Any}("name" => "University of British Columbia", "institution_id" => 57, "type" => 2)
 Dict{String, Any}("name" => "Nanjing University of Aeronautics and Astronautics", "institution_id" => 3437, "type" => 5)
 Dict{String, Any}("name" => "Taylor's University", "institution_id" => 1955, "type" => 5)
 Dict{String, Any}("name" => "Sabancı University", "institution_id" => 914, "type" => 4)
 Dict{String, Any}("name" => "Concordia University", "institution_id" => 140, "type" => 3)

In [7]:
api_allocation = Dict{}()
for entry in tier_data
    api_allocation[entry["name"]] = entry["type"]
end
NUMBER_OF_TYPES = maximum(values(api_allocation)) + 1 # accomodate departments with no type allocation

6

Here we can control which sinks we wish to display. Teaching universities must always be included:

In [8]:
# sink of teaching universities that do not graduate PhDs
# this must be constructed using academic placements, not pre-defined sink placements

teaching_universities = Set() 
for dept_name in academic_to
    if !(dept_name in academic)
        # the department hired an assistant professor but never graduated anyone
        push!(teaching_universities, dept_name)
    end
end

but the rest are more flexible:

In [9]:
public_sector = ("Public Sector", Set())
private_sector = ("Private Sector", Set())
other_groups = ("Other Groups", Set())

postdocs = ("Postdocs", Set())
lecturers = ("Lecturers", Set())
other_academic = ("Other Academic", Set())

for outcome in rough_sink_builder
    if outcome["recruiter_type"] == 5 # government institution
        push!(public_sector[2], (string(outcome["to_name"], " ($(public_sector[1]))"), outcome))
    elseif outcome["recruiter_type"] in [6, 7] # private sector: for and not for profit
        push!(private_sector[2], (string(outcome["to_name"], " ($(private_sector[1]))"), outcome))
    elseif outcome["recruiter_type"] == 8 # international organizations, think tanks, assorted
        push!(other_groups[2], (string(outcome["to_name"], " ($(other_groups[1]))"), outcome))

    # some other examples
    # every example here must also have a corresponding sink Set() above, 
    #     and an entry in sinks_to_include below
   
    elseif outcome["postype"] == 6
        # postdocs that are not in the above (i.e. academic; not public, private, or other)
        # please note that the included JSON does not contain postdocs; use the API
        push!(postdocs[2], (string(outcome["to_name"], " ($(postdocs[1]))"), outcome))
    elseif outcome["postype"] in [5, 7]
        # lecturers that are not in the above
        # please note that the included JSON does not contain lecturers; use the API
        push!(lecturers[2], (string(outcome["to_name"], " ($(lecturers[1]))"), outcome))
    else
        # everything else including terminal academic positions
        # this sink can only be constructed as an "else" statement
        push!(other_academic[2], (string(outcome["to_name"], " ($(other_academic[1]))"), outcome))
    
    end
end

# sort to ensure consistent ordering
academic_list = sort(collect(academic))
teaching_list = sort(collect(teaching_universities))
sinks_to_include = (public_sector, private_sector, other_groups, postdocs, lecturers, other_academic)

sink_builder, sinks, sink_labels = SBM_flexible.build_sinks(sinks_to_include, teaching_list)

NUMBER_OF_SINKS = length(sink_labels)
numtotal = NUMBER_OF_TYPES + NUMBER_OF_SINKS
institutions = vcat(academic_list, sinks...)
println("$(length(academic_list)) academic departments, $(length(institutions)) total departments")

Including the following sinks:
 Public Sector
 Private Sector
 Other Groups
 Postdocs
 Lecturers
 Other Academic
 Teaching Universities
Total 7 sinks
870 academic departments, 3647 total departments

We also need the adjacency matrix:

In [10]:
length(academic_builder) + length(sink_builder)

17364

In [11]:
out = SBM_flexible.get_adjacency(academic_list, institutions, academic_builder, sink_builder);

Total 17364 Placements (found 17364 by sequence counting, 17364 by matrix sum)

In [12]:
sum(out)

17364

as well as the assembled mapping between institution names and types:

In [13]:
sorted_allocation = Vector{Int32}(undef, length(institutions))
cursor = 1

for institution_name in academic_list
    if institution_name in keys(api_allocation)
        sorted_allocation[cursor] = api_allocation[institution_name]
    else
        # name not found, collect in last type
        sorted_allocation[cursor] = NUMBER_OF_TYPES
    end
    cursor += 1
end

for (i, sink_list) in enumerate(sinks)
    for _ in sink_list
        sorted_allocation[cursor] = NUMBER_OF_TYPES + i # the sinks must stay in fixed types
        cursor += 1
    end
end

This allows us to compute the results:

In [14]:
placement_rates, counts, full_likelihood = SBM_flexible.bucket_extract(sorted_allocation, out, NUMBER_OF_TYPES, numtotal)

(Int32[770 119 … 4 2; 709 373 … 15 10; … ; 254 280 … 214 21; 374 523 … 155 21], Int32[289 697 … 7718 544; 697 1681 … 18614 1312; … ; 9758 23534 … 260596 18368; 12121 29233 … 323702 22816], -81206.13779041327)

In [15]:
placement_rates

13×6 Matrix{Int32}:
 770  119   46   15    4   2
 709  373  121   45   15  10
 706  660  336  110   25  27
 493  702  422  242   44  20
  28   76   85   78  104   5
  18    7    6    2    3   5
 591  491  303  139   58  12
 768  449  262  127   48   7
 201  160  108   59   28   3
 654  689  690  495  293  47
 149  229  204  230  151  12
 254  280  309  294  214  21
 374  523  509  320  155  21

In [16]:
placement_rates ./ counts # means

13×6 Matrix{Float64}:
 2.66436     0.170732    0.0267909   0.00392157   0.000518269  0.00367647
 1.01722     0.221892    0.02922     0.00487805   0.000805845  0.00762195
 0.411182    0.159382    0.0329379   0.00484048   0.000545209  0.00835396
 0.128889    0.0760976   0.0185699   0.00478025   0.000430739  0.00277778
 0.00362788  0.00408295  0.00185371  0.000763583  0.00050457   0.000344163
 0.0330882   0.00533537  0.00185644  0.000277778  0.000206498  0.00488281
 0.203302    0.0700328   0.0175439   0.00361274   0.000747095  0.00219298
 0.187454    0.0454407   0.0107637   0.00234209   0.000438701  0.000907676
 0.257033    0.0848356   0.0232458   0.00570048   0.00134074   0.00203804
 0.0649841   0.0283866   0.01154     0.00371622   0.00109016   0.002481
 0.0199198   0.012694    0.00459046  0.00232323   0.000755907  0.000852273
 0.0260299   0.0118977   0.00532998  0.00227642   0.000821194  0.00114329
 0.0308555   0.0178907   0.00706817  0.0019947    0.000478835  0.000920407

In [17]:
# if there are missing departments below that belong in higher tiers, this metric may not be useful
# to fix, filter the academic placements in the API data to only have institutions from tier_data
# or create a new tier_data type allocation containing all academic institutions
full_likelihood

-81206.13779041327

In [18]:
SBM_flexible.nice_table(placement_rates, NUMBER_OF_TYPES, NUMBER_OF_SINKS, sink_labels; has_unassigned = true)

┌───────────────────────┬────────┬────────┬────────┬────────┬────────┬─────────┬────────────┐
│                       │ Tier 1 │ Tier 2 │ Tier 3 │ Tier 4 │ Tier 5 │ Missing │ Row Totals │
├───────────────────────┼────────┼────────┼────────┼────────┼────────┼─────────┼────────────┤
│                Tier 1 │    770 │    119 │     46 │     15 │      4 │       2 │        956 │
│                Tier 2 │    709 │    373 │    121 │     45 │     15 │      10 │       1273 │
│                Tier 3 │    706 │    660 │    336 │    110 │     25 │      27 │       1864 │
│                Tier 4 │    493 │    702 │    422 │    242 │     44 │      20 │       1923 │
│                Tier 5 │     28 │     76 │     85 │     78 │    104 │       5 │        376 │
│               Missing │     18 │      7 │      6 │      2 │      3 │       5 │         41 │
│         Public Sector │    591 │    491 │    303 │    139 │     58 │      12 │       1594 │
│        Private Sector │    768 │    449 │    262 │    127 │     48 │       7 │       1661 │
│          Other Groups │    201 │    160 │    108 │     59 │     28 │       3 │        559 │
│              Postdocs │    654 │    689 │    690 │    495 │    293 │      47 │       2868 │
│             Lecturers │    149 │    229 │    204 │    230 │    151 │      12 │        975 │
│        Other Academic │    254 │    280 │    309 │    294 │    214 │      21 │       1372 │
│ Teaching Universities │    374 │    523 │    509 │    320 │    155 │      21 │       1902 │
│         Column Totals │   5715 │   4758 │   3401 │   2156 │   1142 │     192 │      17364 │
└───────────────────────┴────────┴────────┴────────┴────────┴────────┴─────────┴────────────┘
\begin{tabular}{rrrrrrrr}
  \hline
   & \textbf{Tier 1} & \textbf{Tier 2} & \textbf{Tier 3} & \textbf{Tier 4} & \textbf{Tier 5} & \textbf{Missing} & \textbf{Row Totals} \\\hline
  Tier 1 & 770 & 119 & 46 & 15 & 4 & 2 & 956 \\
  Tier 2 & 709 & 373 & 121 & 45 & 15 & 10 & 1273 \\
  Tier 3 & 706 & 660 & 336 & 110 & 25 & 27 & 1864 \\
  Tier 4 & 493 & 702 & 422 & 242 & 44 & 20 & 1923 \\
  Tier 5 & 28 & 76 & 85 & 78 & 104 & 5 & 376 \\
  Missing & 18 & 7 & 6 & 2 & 3 & 5 & 41 \\
  Public Sector & 591 & 491 & 303 & 139 & 58 & 12 & 1594 \\
  Private Sector & 768 & 449 & 262 & 127 & 48 & 7 & 1661 \\
  Other Groups & 201 & 160 & 108 & 59 & 28 & 3 & 559 \\
  Postdocs & 654 & 689 & 690 & 495 & 293 & 47 & 2868 \\
  Lecturers & 149 & 229 & 204 & 230 & 151 & 12 & 975 \\
  Other Academic & 254 & 280 & 309 & 294 & 214 & 21 & 1372 \\
  Teaching Universities & 374 & 523 & 509 & 320 & 155 & 21 & 1902 \\
  Column Totals & 5715 & 4758 & 3401 & 2156 & 1142 & 192 & 17364 \\\hline
\end{tabular}

In [19]:
for sorted_type in 1:NUMBER_OF_TYPES
    counter = 0
    inst_hold = []
    if sorted_type != NUMBER_OF_TYPES
        println("TYPE $sorted_type:")
    else
        println("MISSING (Unassigned Academic Departments):")
    end
    for (i, sbm_type) in enumerate(sorted_allocation)
        if sbm_type == sorted_type
            push!(inst_hold, institutions[i])
            counter += 1
        end
    end
    for inst in sort(inst_hold)
        println("  ", inst)
    end
    println("Total Institutions: $counter")
    println()
end

TYPE 1:
  Columbia University
  Duke University
  Harvard University
  London School of Economics and Political Science
  Massachusetts Institute of Technology
  New York University
  Northwestern University
  Princeton University
  Stanford University
  University of California Los Angeles (UCLA)
  University of California, Berkeley
  University of Chicago
  University of Maryland
  University of Michigan
  University of Pennsylvania
  University of Wisconsin, Madison
  Yale University
Total Institutions: 17

TYPE 2:
  Arizona State University
  Bocconi University
  Boston College
  Boston University
  Brown University
  Carnegie Mellon University
  Cornell University
  Erasmus University Rotterdam
  European University Institute
  Johns Hopkins University
  Maastricht University
  Michigan State University
  National University of Singapore
  Ohio State University
  Pennsylvania State University
  Purdue University
  Stockholm School of Economics
  Texas A&M University, College Station
  Tilburg University
  Universitat Pompeu Fabra
  University College London
  University of Bonn
  University of British Columbia
  University of California, Davis
  University of California, San Diego
  University of Cambridge
  University of Illinois at Urbana-Champaign
  University of Mannheim
  University of Minnesota, Twin Cities
  University of Nottingham
  University of Oxford
  University of Rochester
  University of Southern California
  University of Texas at Austin
  University of Toronto
  University of Virginia
  University of Warwick
  University of Washington
  Vanderbilt University
  Washington University in St. Louis
  École d'Économie de Paris
Total Institutions: 41

TYPE 3:
  Aarhus University
  Aix-Marseille Université
  American University
  Australian National University
  BI Norwegian Business School
  CEMFI
  Chinese University of Hong Kong
  City University of London
  Clemson University
  Concordia University
  Copenhagen Business School
  ETH Zurich
  Ecole Polytechnique (IP Paris)
  Emory University
  Florida State University
  George Mason University
  George Washington University
  Georgetown University
  Georgia Institute of Technology
  Georgia State University
  Goethe-Universität Frankfurt am Main
  Hong Kong University of Science and Technology
  INSEAD
  Indiana University Bloomington
  Iowa State University
  Kansas State University
  Katholieke Universiteit Leuven
  London Business School
  Ludwig-Maximilians-Universitat München (LMU) (University of Munich)
  Lund University
  McGill University
  McMaster University
  Monash University
  North Carolina State University
  Norwegian School of Economics (NHH)
  Oklahoma State University
  Oregon State University
  Peking University
  Queen Mary University of London
  Queen's University
  Rice University
  Rutgers, The State University of New Jersey
  Sciences Po
  Shanghai University of Finance and Economics
  Simon Fraser University
  Singapore Management University
  Stockholm University
  Stony Brook University (SUNY)
  Syracuse University
  Temple University
  The New School
  Tsinghua University
  Universidad Carlos III de Madrid
  Universitat Autònoma de Barcelona
  University of Alabama
  University of Amsterdam
  University of Arizona
  University of Calgary
  University of California, Irvine
  University of California, Riverside
  University of California, Santa Barbara
  University of California, Santa Cruz
  University of Colorado, Boulder
  University of Connecticut
  University of Copenhagen
  University of Essex
  University of Florida
  University of Georgia
  University of Glasgow
  University of Hawaiʻi at Mānoa
  University of Houston
  University of Illinois at Chicago
  University of Iowa
  University of Kansas
  University of Lausanne
  University of Manchester
  University of Massachusetts, Amherst
  University of Melbourne
  University of Missouri, Columbia
  University of New South Wales (UNSW), Sydney
  University of North Carolina, Chapel Hill
  University of Notre Dame
  University of Oregon
  University of Oslo
  University of Pittsburgh
  University of Texas at Dallas
  University of Vienna
  University of York
  University of Zurich
  Università di Bologna
  Università di Roma Tor Vergata
  Université Catholique de Louvain
  Universíté de Montréal
  Uppsala University
  Utrecht University
  Virginia Tech
  Vrije Universiteit Amsterdam
  Washington State University
  West Virginia University
  Western University
  Xiamen University
Total Institutions: 101

TYPE 4:
  Aalto University
  Aligarh Muslim University
  Auburn University
  Baruch College, City University of New York
  Bentley University
  Bilkent University
  Binghamton University (SUNY)
  Birkbeck College, University of London
  Boğaziçi University
  Brandeis University
  CERGE-EI (Center for Economic Research and Graduate Education – Economics Institute)
  Ca' Foscari University Venice
  California Institute of Technology (Caltech)
  Cardiff University
  Carleton University
  Center for Research in Economics and Statistics (CREST)
  Central European University
  Central University of Finance and Economics
  City University of Hong Kong
  City University of New York Graduate Center
  Claremont Graduate University
  Clark University
  Collegio Carlo Alberto
  Colorado State University
  Dalhousie University
  Deakin University
  Delft University of Technology
  Dongbei University of Finance and Economics
  Drexel University
  Durham University
  ESMT Berlin
  ESSEC Business School
  East Carolina University
  East China Normal University
  Eastern Kentucky University
  Eastern Mediterranean University
  Florida International University
  Fordham University
  Frankfurt School of Finance & Management
  Freie Universität Berlin
  Fudan University
  Fundação Getulio Vargas (FGV)
  Ghent University
  Graduate Institute of International and Development Studies
  HEC Paris
  Hanyang University
  Hebrew University of Jerusalem
  Heidelberg University
  Hong Kong Baptist University
  Hong Kong Polytechnic University
  Howard University
  Humboldt University Berlin
  IE University
  IMT School for Advanced Studies Lucca
  Imperial College London
  Indian Institute of Technology, Kanpur
  Indian Statistical Institute, Delhi
  Indira Gandhi Institute of Development Research (IGIDR)
  Insper (Institute of Education and Research)
  Instituto Tecnologico Autónomo de Mexico (ITAM)
  Jawaharlal Nehru University
  Jinan University
  Johannes Kepler University Linz
  King's College London
  Korea University
  Koç University
  LUISS Guido Carli
  Lancaster University
  Lehigh University
  Leiden University
  Louisiana State University
  Miami University
  Middle Tennessee State University
  Mississippi State University
  Nanyang Technological University
  National Central University
  National Research University Higher School of Economics, Moscow
  National Taiwan University
  New Economic School
  New Mexico State University
  New York University Abu Dhabi
  New York University Shanghai
  Northeastern University
  Osaka University
  Pardee RAND Graduate School
  Pontifical Catholic University of Rio de Janeiro
  Pontificia Universidad Católica de Chile
  Queens' University Belfast
  Queensland University of Technology
  Radboud University
  Rensselaer Polytechnic Institute
  Royal Holloway, University of London
  Royal Melbourne Institute of Technology (RMIT)
  Rutgers University, Newark
  SOAS (School of Oriental and African Studies), University of London
  SUNY Buffalo State
  Sabancı University
  Sapienza Università di Roma
  Seoul National University
  Shandong University
  Shiv Nadar University
  Sogang University
  Southern Methodist University
  Southwestern University of Finance and Economics
  State University of New York at Buffalo
  Sun Yat-Sen University
  Technische Universität Berlin
  Tel Aviv University
  Texas Tech University
  Toronto Metropolitan University
  Trinity College Dublin, University of Dublin
  Tufts University
  Tulane University
  Universidad Complutense de Madrid
  Universidad de Alicante
  Universidad de Chile
  Universidad de Navarra
  Universidad de los Andes
  Universidad del Rosario
  Universidade Nova de Lisboa
  Universitat de Barcelona
  Universiti Utara Malaysia
  University College Dublin
  University at Albany (SUNY)
  University of Adelaide
  University of Alberta
  University of Arkansas
  University of Bath
  University of Bern
  University of Birmingham
  University of Bristol
  University of Cape Town
  University of Cincinnati
  University of Cologne
  University of Colorado, Denver
  University of Delaware
  University of East Anglia
  University of Edinburgh
  University of Exeter
  University of Gothenburg
  University of Groningen
  University of Guelph
  University of Göttingen
  University of Helsinki
  University of Hong Kong
  University of Innsbruck
  University of International Business and Economics
  University of Jena
  University of Kent
  University of Kentucky
  University of Konstanz
  University of Leeds
  University of Leicester
  University of Liverpool
  University of Louisville
  University of Maine, Orono
  University of Manitoba
  University of Memphis
  University of Miami
  University of Minho
  University of Mississippi
  University of Nebraska, Lincoln
  University of Nevada, Las Vegas (UNLV)
  University of Nevada, Reno
  University of New Hampshire
  University of New Mexico
  University of North Carolina, Charlotte
  University of North Carolina, Greensboro
  University of North Texas
  University of Oklahoma
  University of Ottawa
  University of Queensland
  University of Reading
  University of Rhode Island
  University of Sheffield
  University of South Carolina
  University of South Florida
  University of Southampton
  University of Southern Denmark
  University of St Andrews
  University of St. Gallen
  University of Strathclyde
  University of Surrey
  University of Sussex
  University of Sydney
  University of São Paulo
  University of Technology Sydney
  University of Tennessee, Knoxville
  University of Texas at Arlington
  University of Texas at El Paso
  University of Texas at San Antonio
  University of Tokyo
  University of Utah
  University of Victoria
  University of Waterloo
  University of Western Australia
  University of Wisconsin, Milwaukee
  University of Wyoming
  Università Cattolica del Sacro Cuore
  Università Degli Studi di Milano
  Università degli Studi di Padova
  Università degli Studi di Pavia
  Università degli Studi di Torino
  Università degli Studi di Trento
  Università degli Studi di Verona
  Università della Svizzera Italiana
  Université Laval
  Université Libre de Bruxelles
  Université Paris 1 Panthéon-Sorbonne
  Université Paris-Dauphine
  Université de Genève
  Université du Québec à Montréal (UQAM)
  Utah State University
  Victoria University of Wellington
  Vienna Graduate School of Finance (VGSF)
  Vienna University of Economics and Business
  Waseda University
  Wayne State University
  Wilfrid Laurier University
  Wuhan University
  York University
  Zhejiang University
  Zhongnan University of Economics and Law
  Özyeğin University
  İzmir University of Economics
Total Institutions: 225

TYPE 5:
  Aalborg University
  Academy of Postgraduate Education (Академия последипломного образования)
  AgroParisTech
  Alexandria University
  Allameh Tabataba'i University
  Amity University
  Anadolu University
  Anglia Ruskin University
  Aristotle University of Thessaloniki
  Aston University
  Athens University of Economics and Business
  Auckland University of Technology
  Aveiro University
  Babcock University
  Ball State University
  Banco de Portugal
  Bank of Finland
  Barcelona School of Economics
  Bayero University, Kano
  Beijing Institute of Technology
  Bharathiar University
  Bharathidasan University
  Bielefeld University
  Bond University
  Bournemouth University
  Brunel University London
  Bucharest Academy of Economic Studies
  Budapest University of Technology and Economics
  COMSATS University Islamabad
  CY Cergy Paris Université
  Cairo University
  California State Polytechnic University, Pomona
  Carl von Ossietzky Universität Oldenburg
  Central Michigan University
  Charles University
  Chinese Academy of Sciences
  Chr. Michelsen Institute (CMI)
  Chung-Ang University
  Cochin University of Science and Technology
  Colorado School of Mines
  Corvinus University of Budapest
  Covenant University
  Coventry University
  Cranfield University
  Curtin University
  Dalian University of Technology
  De Montfort University
  Devi Ahilya Vishwavidyalaya, Indore
  Drew University
  Dublin City University
  Dublin Institute of Technology
  EDHEC Business School
  ENSAE Paris Tech
  ESCP Business School
  Ecole des Hautes Etudes en Sciences Sociales (EHESS)
  Edith Cowan University
  Ege University
  Eindhoven University of Technology
  Emlyon Business School
  FUCAPE Business School
  Federal Reserve Bank of New York
  Federal University of Paraná
  Federal University of Rio de Janeiro
  Federal University of Technology Akure
  Ferdowsi University of Mashhad
  Florida Atlantic University
  Friedrich-Alexander-Universität Erlangen-Nürnberg
  Galatasaray University
  Gauhati University
  Glasgow Caledonian University
  Gomal University
  Grenoble Ecole de Management
  Griffith University
  Guangxi University
  Halle Institute for Economic Research (IWH)
  Hamburg University
  Hanken School of Economics
  Harbin Institute of Technology
  Heinrich Heine University Dusseldorf
  Helwan University
  Heriot Watt University
  Hunter College, CUNY
  ICFAI Foundation for Higher Education
  ISM University of Management and Economics
  ITMO University
  Illinois Institute of Technology
  Indian Institute of Foreign Trade
  Indian Institute of Management Ahmedabad
  Indian Institute of Management Bangalore
  Indian Institute of Management Indore
  Indian Institute of Management Kozhikode
  Indian Institute of Science
  Indian Institute of Technology, Bombay
  Indian Institute of Technology, Delhi
  Indian Institute of Technology, Indore
  Indian Institute of Technology, Kharagpur
  Indian Institute of Technology, Madras
  Indian Statistical Institute, Kolkata
  Indiana Institute of Technology
  Indiana University Purdue University Indianapolis (IUPUI)
  Indira Gandhi University, Meerpur, Rewari
  Inner Mongolia Agriculture Univeristy
  Institut Agro Montpellier
  Institut national de recherche pour l'agriculture, l'alimentation et l'environnement (INRAE)
  Institute for Advanced Study in Toulouse
  Institute of Technology Sligo
  Instituto Politécnico Nacional (IPN)
  Instituto Universitário de Lisboa, ISCTE-IUL
  Instituto de Matemática Pura e Aplicada (IMPA)
  International Centre for Education in Islamic Finance
  International Islamic University Malaysia
  International Islamic University, Islamabad
  International Monetary Fund (IMF)
  International Trade Centre
  Iran University of Science and Tchnology
  Istanbul Bilgi University
  Istanbul University
  Jadavpur University
  Jaypee Institute of Information Technology
  Jilin University
  Jiwaji University
  Julius-Maximilians-Universität Würzburg
  Justus-Liebig-Universität Gießen
  Jönköping University
  K. N. Toosi University of Technology
  KTH Royal Institute of Technology
  Kangwon National University
  Karamanoğlu Mehmetbey Üniversitesi
  Katholische Universität Eichstätt-Ingolstadt
  Kiel Institute for the World Economy
  Kiel University
  Kingston University London
  Kobe University
  Korea Advanced Institute of Science and Technology (KAIST)
  Kurukshetra University
  Kwara State University
  Kyoto University
  Lahore School of Economics
  Leibniz Universität Hannover
  Leipzig University
  Libera Università di Bolzano
  Limkokwing University
  Linköping University
  Linnéuniversitetets
  Lomonosov Moscow State University (Московский государственный университет имени М. В. Ломоносова)
  Loughborough University
  Luleå University of Technology
  MINES ParisTech
  Macquarie University
  Maharshi Dayanand Saraswati University, Ajmer
  Manchester Metropolitan University
  Manchester University
  Marietta College
  Marmara University
  Martin Luther University of Halle-Wittenberg
  Massey University
  Maulana Azad National Institute of Technology Bhopal (MANIT)
  Meiji University
  Middle East Technical University
  Middle East Technical University - Northern Cyprus Campus
  Multimedia University
  Nanjing University of Aeronautics and Astronautics
  National Graduate Institute for Policy Studies (GRIPS), Japan
  National Institute of Development Administration
  National Research University Higher School of Economics, St. Petersburg
  National University of Computer & Emerging Sciences
  National University of Sciences and Technology (NUST)
  Near East University
  Nelson Mandela University
  Newcastle University
  Nnamdi Azikiwe University
  Norges Artiske Universitet
  North-West University
  Northern Illinois University
  Norwegian University of Life Sciences
  Norwegian University of Science and Technology
  Nottingham Trent University
  Obafemi Awolowo University
  Old Dominion University
  Otto-von-Guericke University Magdeburg
  Oxford Brookes University
  Paderborn University
  Pan-Atlantic University
  Penn State Abington
  Philipps University Marburg
  Politecnico di Torino
  Punjabi University Patiala
  Pusan National University
  Quaid-i-Azam University
  RAND Corporation
  RWTH Aachen University
  Rabindra Bharati University
  Recinto Universitario de Mayagüez, University of Puerto Rico
  Ritsumeikan Asia Pacific University
  Ruhr Graduate School in Economics
  Ruhr University Bochum
  SKEMA Business School
  SWPS University of Social Sciences and Humanities
  Saint Mary's University (SMU)
  Saint Petersburg University
  Sam Houston State University
  Sant'Anna School of Advanced Studies
  Sari Agricultural Sciences and Natural Resources University
  Savitribai Phule Pune University
  Sciences Po Toulouse
  Scuola Normale Superiore
  Sharif University of Technology
  Sorbonne Université
  South Asian University
  Southern Illinois University
  Southern Illinois University, Carbondale
  Ss. Cyril and Methodius University in Skopje (Универзитет „Св. Кирил и Методиј“ во Скопје)
  St. Petersburg State University of Economics
  St. Thomas University
  Staffordshire University
  Stellenbosch University
  Stevens Institute of Technology
  Stripe
  Suffolk University
  Sultan Qaboos University
  Swedish University of Agricultural Sciences
  Swiss Tropical and Public Health Institute
  Symbiosis International (Deemed University)
  Tallinn University of Technology
  Tampere University
  Tarbiat Modares University
  Taylor's University
  Technical University of Crete
  Technical University of Denmark
  Technical University of Munich
  Technion
  Technische Universität Braunschweig
  Technische Universität Dortmund
  Technische Universität Dresden
  Technological University Dublin
  Tecnológico de Monterrey
  Telecom ParisTech
  Texas A&M International University
  Thammasat University
  Tohoku University
  Towson University
  Umeå University
  Union College
  Universidad Anáhuac
  Universidad Europea de Madrid
  Universidad Nacional Autónoma de México (UNAM)
  Universidad Nacional de Córdoba
  Universidad Politécnica de Madrid
  Universidad Pontificia Comillas
  Universidad Publica de Navarra
  Universidad Rey Juan Carlos
  Universidad de Cantabria
  Universidad de Castilla-La Mancha
  Universidad de Deusto
  Universidad de Granada
  Universidad de Málaga
  Universidad de Salamanca
  Universidad de Valladolid
  Universidad de Vigo
  Universidad de Zaragoza
  Universidad del País Vasco / Euskal Herriko Unibertsitatea
  Universidade Tecnológica Federal do Paraná
  Universidade da Coruña
  Universitat Jaume I
  Universitat Politecnica de Catalunya
  Universitat Ramon Llull