In [1]:
using JSON
using Random
using Distributions
using MySQL
using DotEnv
using DataFrames
using PrettyTables
cfg = DotEnv.config()
const DB = DBInterface
NUM=5

5

In [2]:
#query = "insert into bootstrap_trials set trial_time=now(),sample_size=?,number_of_tiers=?"
#    create_trial_statement =  DBInterface.prepare(d, query);

In [3]:
 d = DBInterface.connect(MySQL.Connection,cfg["host"], cfg["user"], cfg["password"], db =cfg["database"], port = parse(Int64,cfg["port"]));
query = "select i.name,j.institution_id ,
SUM(CASE
  WHEN j.estimated_tier = 1 THEN count ELSE 0 END
) AS TIER1,
SUM(CASE
  WHEN j.estimated_tier = 2 THEN count ELSE 0 END
) AS TIER2,
SUM(CASE
  WHEN j.estimated_tier = 3 THEN count ELSE 0 END
) AS TIER3,
SUM(CASE
  WHEN j.estimated_tier = 4 THEN count ELSE 0 END
) AS TIER4,
SUM(CASE
  WHEN j.estimated_tier = 5 THEN count ELSE 0 END
) AS TIER5

from ftrecruiter.institutions i join
(select d.institution_id, d.estimated_tier, count(*) as count from bootstrap_data d left join bootstrap_trials t  
on t.trial_id=d.trial_id where t.number_of_tiers=?
group by institution_id, estimated_tier) j on i.institution_id=j.institution_id
group by j.institution_id"
get_institutions =  DBInterface.prepare(d, query);
m = DB.execute(get_institutions, [NUM]) |> DataFrame
println(m)
DB.close!(d)

752×7 DataFrame
 Row │ name                               institution_id  TIER1    TIER2    TIER3    TIER4    TIER5
     │ String?                            Int32?          Dec64…?  Dec64…?  Dec64…?  Dec64…?  Dec64…?
─────┼────────────────────────────────────────────────────────────────────────────────────────────────
   1 │ University of California, San Di…               1      2.0     86.0     30.0      0.0      0.0
   2 │ University of California Los Ang…               6    116.0      1.0      1.0      0.0      0.0
   3 │ University of Maryland                         13    116.0      1.0      1.0      0.0      0.0
   4 │ Syracuse University                            15      0.0     15.0    101.0      2.0      0.0
   5 │ Brandeis University                            16      0.0      1.0      9.0     61.0     12.0
   6 │ Duke University                                17    116.0      1.0      1.0      0.0      0.0
   7 │ Northwestern University                        18    116.0      0.0      0.0      2.0      0.0
   8 │ Tufts University                               19      0.0      1.0     19.0     56.0     11.0
   9 │ Brown University                               21      6.0    111.0      1.0      0.0      0.0
  10 │ Columbia University                            22    116.0      1.0      0.0      1.0      0.0
  11 │ Instituto Tecnologico Autónomo d…              23      0.0      1.0     56.0     27.0      8.0
  12 │ University of Pittsburgh                       26      0.0     13.0    101.0      4.0      0.0
  13 │ Rice University                                27      0.0      4.0    109.0      5.0      0.0
  14 │ Boston University                              29     49.0     68.0      1.0      0.0      0.0
  15 │ RAND Corporation                               31      0.0      0.0      0.0     12.0     78.0
  16 │ University of Toronto                          32     16.0    102.0      0.0      0.0      0.0
  17 │ Michigan State University                      33      2.0    116.0      0.0      0.0      0.0
  18 │ Universitat Autònoma de Barcelona              38      0.0     32.0     84.0      2.0      0.0
  19 │ IMT School for Advanced Studies …              39      0.0      1.0     19.0     80.0     18.0
  20 │ Johns Hopkins University                       40      2.0    116.0      0.0      0.0      0.0
  21 │ University of Connecticut                      42      1.0      8.0    106.0      3.0      0.0
  22 │ University of Texas at Austin                  46      2.0    116.0      0.0      0.0      0.0
  23 │ Eastern Kentucky University                    55      0.0      1.0     21.0     52.0     44.0
  24 │ University of British Columbia                 57      2.0    116.0      0.0      0.0      0.0
  25 │ Maastricht University                          59      2.0     97.0     17.0      2.0      0.0
  26 │ Carleton University                            60      0.0      1.0     51.0     55.0     11.0
  27 │ Vrije Universiteit Amsterdam                   61      2.0     51.0     63.0      2.0      0.0
  28 │ University of California, Santa …              66      1.0     33.0     81.0      3.0      0.0
  29 │ Australian National University                 67      0.0      2.0     88.0     25.0      3.0
  30 │ Hong Kong University of Science …              68      0.0      6.0    106.0      4.0      2.0
  31 │ University of Virginia                         70      2.0    116.0      0.0      0.0      0.0
  32 │ Washington University in St. Lou…              72      2.0    116.0      0.0      0.0      0.0
  33 │ University of Wisconsin, Madison               73    116.0      1.0      1.0      0.0      0.0
  34 │ Purdue University                              74      2.0    116.0      0.0      0.0      0.0
  35 │ Rutgers University, Newark                     77      0.0      0.0      1.0     36.0     21.0
  36 │ Stanford University                            78    116.0      0.0      0.0      2.0      0.0
  37 │ Sogang University                              80      0.0      0.0      3.0     36.0     13.0
  38 │ Clemson University                             81      1.0     18.0     97.0      2.0      0.0
  39 │ University of South Carolina                   82      0.0      1.0     46.0     58.0     13.0
  40 │ University of New South Wales (U…              83      0.0      1.0     67.0     43.0      7.0
  41 │ Colorado School of Mines                       84      0.0      0.0      4.0     56.0     57.0
  42 │ Georgetown University                          85      1.0     11.0    104.0      2.0      0.0
  43 │ Toulouse School of Economics                   86      2.0    114.0      1.0      1.0      0.0
  44 │ Universíté de Montréal                         87      0.0      1.0    106.0     10.0      1.0
  45 │ University of California, Davis                89      2.0    116.0      0.0      0.0      0.0
  46 │ University College London                      90      2.0    114.0      0.0      2.0      0.0
  47 │ University of Washington                       91      2.0    116.0      0.0      0.0      0.0
  48 │ University of Hong Kong                        92      0.0      1.0     56.0     48.0      9.0
  49 │ Universidad Carlos III de Madrid               94      1.0     39.0     76.0      2.0      0.0
  50 │ Monash University                              95      0.0      8.0    106.0      4.0      0.0
  51 │ Wilfrid Laurier University                     96      0.0      0.0      2.0     44.0     14.0
  52 │ CEMFI                                          97      0.0      5.0    108.0      5.0      0.0
  53 │ Pusan National University                     100      0.0      0.0      0.0      9.0     79.0
  54 │ University of Illinois at Chicago             101      0.0      2.0    109.0      7.0      0.0
  55 │ University of Texas at Arlington              103      0.0      0.0      1.0     68.0     49.0
  56 │ University of Notre Dame                      104      1.0     51.0     65.0      1.0      0.0
  57 │ Rutgers, The State University of…             105      0.0      5.0    111.0      2.0      0.0
  58 │ University of Cyprus                          107      0.0      0.0      0.0     14.0     44.0
  59 │ University of Cincinnati                      109      0.0      0.0      4.0     33.0     14.0
  60 │ Université du Québec à Montréal …             112      0.0      1.0     27.0     73.0     13.0
  61 │ Mississippi State University                  113      0.0      0.0      7.0     66.0     16.0
  62 │ Universidad de Alicante                       116      0.0      0.0     15.0     83.0     20.0
  63 │ Royal Holloway, University of Lo…             117      0.0      0.0     13.0     76.0     29.0
  64 │ University of Cambridge                       120      2.0     73.0     42.0      1.0      0.0
  65 │ Sam Houston State University                  121      0.0      0.0      1.0     36.0     17.0
  66 │ University of Warwick                         124      2.0    113.0      1.0      2.0      0.0
  67 │ University of Southern California             125      2.0    116.0      0.0      0.0      0.0
  68 │ University of Luxembourg                      132      0.0      0.0      1.0     45.0     60.0
  69 │ Pennsylvania State University                 134     18.0    100.0      0.0      0.0      0.0
  70 │ University of Pennsylvania                    137    116.0      1.0      1.0      0.0      0.0
  71 │ Concordia University                          140      0.0      1.0     58.0     51.0      8.0
  72 │ New York University                           144    116.0      1.0      1.0      0.0      0.0
  73 │ University of Missouri, Columbia              150      0.0      2.0    106.0     10.0      0.0
  74 │ University of Calgary                         153      0.0      1.0     95.0     21.0      1.0
  75 │ Toronto Metropolitan University               154      0.0      1.0     58.0     50.0      9.0
  76 │ University of Tennessee, Knoxvil…             155      0.0      1.0     37.0     69.0     11.0
  77 │ Carnegie Mellon University                    158      2.0    115.0      1.0      0.0      0.0
  78 │ Ludwig-Maximilians-Universitat M…             163      0.0      4.0    108.0      6.0      0.0
  79 │ University of Miami                           169      0.0      1.0     47.0     57.0     12.0
  80 │ Université Lumière Lyon 2                     170      0.0      0.0      0.0     16.0     75.0
  81 │ Uppsala University                            173      0.0      2.0    110.0      6.0      0.0
  82 │ University of Mannheim                        175      2.0    114.0      1.0      1.0      0.0
  83 │ Katholieke Universiteit Leuven                176      0.0      4.0    102.0     12.0      0.0
  84 │ New York University Abu Dhabi                 177      0.0      1.0      2.0     42.0     12.0
  85 │ École d'Économie de Paris                     179      2.0    106.0      8.0      2.0      0.0
  86 │ Universitat Pompeu Fabra                      180      2.0    112.0      2.0      2.0      0.0
  87 │ Universidad de Navarra                        181      0.0      1.0     56.0     49.0     11.0
  88 │ University of Bonn                            184      2.0    112.0      2.0      2.0      0.0
  89 │ University of Oxford                          186     26.0     90.0      2.0      0.0      0.0
  90 │ University of Arizona                         187      2.0     69.0     47.0      0.0      0.0
  91 │ Ecole Polytechnique (IP Paris)                188      0.0      1.0     92.0     25.0      0.0
  92 │ University of York                            193      0.0      1.0     39.0     72.0      6.0
  93 │ University of Delaware                        194      0.0      1.0     66.0     43.0      7.0
  94 │ ESSEC Business School                         196      0.0      1.0      5.0     66.0     44.0
  95 │ University of Konstanz                        197      0.0      0.0     12.0     83.0     23.0
  96 │ Universidad Complutense de Madrid             198      0.0      0.0      4.0     71.0     41.0
  97 │ Copenhagen Business School                    199      0.0      1.0     66.0     39.0     10.0
  98 │ Howard University                             200      0.0      0.0      4.0     75.0     38.0
  99 │ University of Bern                            201      0.0      0.0      4.0     77.0     36.0
 100 │ Aarhus University                             206      0.0      1.0     96.0     15.0      6.0
 101 │ Graduate Institute of Internatio…             208      0.0      0.0     18.0     83.0     17.0
 102 │ Universitat Rovira i Virgili                  213      0.0      0.0      0.0     44.0     73.0
 103 │ University of Groningen                       215      0.0      1.0     57.0     53.0      7.0
 104 │ University of Rochester                       218      2.0    116.0      0.0      0.0      0.0
 105 │ University of East Anglia                     220      0.0      0.0      9.0     87.0     22.0
 106 │ Universitat de València                       223      0.0      1.0      4.0     57.0     55.0
 107 │ University of Louisville                      224      0.0      0.0      4.0     40.0     11.0
 108 │ International Monetary Fund (IMF)             225      0.0      0.0      0.0     19.0     81.0
 109 │ Florida International University              229      0.0      1.0     30.0     69.0     18.0
 110 │ University of Cape Town                       235      0.0      0.0      0.0     36.0     80.0
 111 │ Middle East Technical University              236      0.0      0.0      0.0     27.0     86.0
 112 │ University of New Mexico                      239      0.0      0.0     36.0     69.0     13.0
 113 │ Indian Institute of Technology, …             240      0.0      1.0      9.0     77.0     13.0
 114 │ Université de Strasbourg                      244      0.0      0.0      0.0     17.0     91.0
 115 │ Università di Bologna                         246      0.0     38.0     78.0      2.0      0.0
 116 │ ENSAE Paris Tech                              247      0.0      0.0      0.0     18.0     36.0
 117 │ Georgia Institute of Technology               249      0.0      1.0     91.0     19.0      7.0
 118 │ University of North Carolina, Gr…             250      0.0      0.0      5.0     66.0     19.0
 119 │ University of Nevada, Las Vegas …             252      0.0      0.0      1.0     45.0      9.0
 120 │ University of Vienna                          254      0.0      6.0    110.0      2.0      0.0
 121 │ University of Zurich                          255      0.0     21.0     93.0      4.0      0.0
 122 │ Universitat de Barcelona                      259      0.0      0.0     25.0     80.0     13.0
 123 │ Birkbeck College, University of …             264      0.0      1.0     49.0     60.0      8.0
 124 │ University of Queensland                      266      0.0      1.0     62.0     50.0      5.0
 125 │ University of Southern Denmark                268      0.0      0.0      6.0     71.0     22.0
 126 │ Université Laval                              274      0.0      1.0      8.0     87.0     22.0
 127 │ University of Porto                           276      0.0      0.0      0.0     32.0     84.0
 128 │ European University Institute                 277      2.0    108.0      6.0      2.0      0.0
 129 │ University of Massachusetts, Amh…             284      0.0      1.0     88.0     22.0      7.0
 130 │ Simon Fraser University                       286      1.0     24.0     92.0      1.0      0.0
 131 │ University of Melbourne                       288      0.0      2.0    111.0      5.0      0.0
 132 │ Yale University                               290    116.0      0.0      0.0      2.0      0.0
 133 │ ETH Zurich                                    295      0.0      1.0     99.0     17.0      1.0
 134 │ Universidad Publica de Navarra                299      0.0      0.0      0.0     20.0     65.0
 135 │ Collegio Carlo Alberto                        301      0.0      1.0      7.0     58.0     10.0
 136 │ American University                           302      0.0      2.0    110.0      6.0      0.0
 137 │ Temple University                             303      0.0      1.0     80.0     29.0      8.0
 138 │ University of Houston                         304      0.0      3.0    110.0      5.0      0.0
 139 │ University of Arkansas                        308      0.0      0.0     38.0     68.0     12.0
 140 │ Fundação Getulio Vargas (FGV)                 309      0.0      1.0     31.0     74.0     11.0
 141 │ Massachusetts Institute of Techn…             311    114.0      2.0      0.0      2.0      0.0
 142 │ Boston College                                312      2.0    116.0      0.0      0.0      0.0
 143 │ New Economic School                           317      0.0      1.0     46.0     57.0     13.0
 144 │ University of Waterloo                        318      0.0      0.0      9.0     79.0     29.0
 145 │ Drew University                               319      0.0      0.0      0.0     13.0     41.0
 146 │ Florida State University                      324      0.0      3.0    110.0      5.0      0.0
 147 │ University of Lausanne                        326      0.0      6.0    107.0      5.0      0.0
 148 │ Özyeğin University                            330      0.0      0.0      2.0     64.0     33.0
 149 │ Aalto University                              332      0.0      0.0     49.0     61.0      8.0
 150 │ University of Edinburgh                       333      0.0      1.0     40.0     69.0      8.0
 151 │ Southern Methodist University                 336      0.0      1.0     78.0     26.0     11.0
 152 │ University of Chicago                         339    116.0      0.0      0.0      2.0      0.0
 153 │ Sciences Po                                   342      0.0      9.0    108.0      1.0      0.0
 154 │ University of Helsinki                        343      0.0      0.0      9.0     71.0     38.0
 155 │ Vanderbilt University                         347      2.0    116.0      0.0      0.0      0.0
 156 │ Harvard University                            350    116.0      0.0      0.0      2.0      0.0
 157 │ London School of Economics and P…             351    116.0      1.0      1.0      0.0      0.0
 158 │ University of Georgia                         358      0.0      7.0    108.0      3.0      0.0
 159 │ Cornell University                            361     13.0    105.0      0.0      0.0      0.0
 160 │ Lancaster University                          362      0.0      0.0     10.0     80.0     28.0
 161 │ University of Essex                           366      2.0     54.0     60.0      2.0      0.0
 162 │ University of Sussex                          368      0.0      1.0     66.0     47.0      4.0
 163 │ Arizona State University                      370      2.0     92.0     23.0      1.0      0.0
 164 │ South Asian University                        374      0.0      0.0      0.0     10.0     52.0
 165 │ SKEMA Business School                         384      0.0      0.0      0.0     42.0     60.0
 166 │ Chr. Michelsen Institute (CMI)                394      0.0      0.0      4.0     54.0     59.0
 167 │ University College Dublin                     398      0.0      1.0     15.0     85.0     17.0
 168 │ Georgia State University                      401      0.0      3.0    112.0      3.0      0.0
 169 │ McMaster University                           409      0.0      2.0     90.0     23.0      3.0
 170 │ George Washington University                  411      1.0     19.0     96.0      2.0      0.0
 171 │ University of Leicester                       412      0.0      1.0     61.0     55.0      1.0
 172 │ University of Haifa                           416      0.0      0.0      1.0     39.0     34.0
 173 │ McGill University                             421      0.0      7.0    109.0      2.0      0.0
 174 │ Universidad de Cantabria                      426      0.0      0.0      0.0     13.0     73.0
 175 │ Dalian University of Technology               427      0.0      0.0      0.0      8.0     51.0
 176 │ Dalhousie University                          429      0.0      1.0      8.0     79.0     21.0
 177 │ Stockholm University                          433      0.0     11.0    105.0      2.0      0.0
 178 │ University of Technology Sydney               435      0.0      0.0      1.0     49.0     27.0
 179 │ Queen's University                            442      0.0      2.0     85.0     27.0      4.0
 180 │ Johannes Kepler University Linz               444      0.0      0.0      4.0     62.0     52.0
 181 │ Xiamen University                             445      0.0      1.0     95.0     10.0      7.0
 182 │ Western Kentucky University                   450      0.0      0.0      0.0     15.0     43.0
 183 │ University of Florida                         452      0.0      4.0    105.0      6.0      3.0
 184 │ Tel Aviv University                           454      0.0      1.0      7.0     83.0     15.0
 185 │ Universidad de los Andes                      460      0.0      1.0     63.0     41.0     13.0
 186 │ Ohio State University                         465      8.0    110.0      0.0      0.0      0.0
 187 │ Washington State University                   466      2.0     93.0     23.0      0.0      0.0
 188 │ University of St. Gallen                      467      0.0      1.0     26.0     78.0     13.0
 189 │ Durham University                             468      0.0      1.0     19.0     83.0     15.0
 190 │ Bilkent University                            469      0.0      0.0     13.0     87.0     18.0
 191 │ Université Clermont Auvergne                  478      0.0      0.0      0.0     18.0     95.0
 192 │ Binghamton University (SUNY)                  485      0.0      1.0     86.0     25.0      6.0

In [4]:
P = zeros(Int32, (NUM, NUM))
i = 0
for r in eachrow(m)
    if r["TIER1"] >= max(r["TIER2"],r["TIER3"],r["TIER4"],r["TIER5"])
        P[1,1] += r["TIER1"]
        P[1,2] += r["TIER2"]
        P[1,3] += r["TIER3"]
        P[1,4] += r["TIER4"]
        P[1,5] += r["TIER5"]
    elseif r["TIER2"] >= max(r["TIER1"],r["TIER3"],r["TIER4"],r["TIER5"])
        P[2,1] += r["TIER1"]
        P[2,2] += r["TIER2"]
        P[2,3] += r["TIER3"]
        P[2,4] += r["TIER4"]
        P[2,5] += r["TIER5"]
    elseif r["TIER3"] >= max(r["TIER1"],r["TIER2"],r["TIER4"],r["TIER5"])
        P[3,1] += r["TIER1"]
        P[3,2] += r["TIER2"]
        P[3,3] += r["TIER3"]
        P[3,4] += r["TIER4"]
        P[3,5] += r["TIER5"]
    elseif r["TIER4"] >= max(r["TIER1"],r["TIER2"],r["TIER3"],r["TIER5"])
        P[4,1] += r["TIER1"]
        P[4,2] += r["TIER2"]
        P[4,3] += r["TIER3"]
        P[4,4] += r["TIER4"]
        P[4,5] += r["TIER5"]
    elseif r["TIER5"] >= max(r["TIER1"],r["TIER2"],r["TIER3"],r["TIER5"])
        P[5,1] += r["TIER1"]
        P[5,2] += r["TIER2"]
        P[5,3] += r["TIER3"]
        P[5,4] += r["TIER4"]
        P[5,5] += r["TIER5"]
    end
end
P

5×5 Matrix{Int32}:
 1970    11      8     17      0
  225  4641    298     28      0
   19   774  10933   2371    376
    0    75   2646  12467   4488
    0     1     61   6099  23988

In [5]:
N = zeros(Float64,(5,5))
for i in 1:NUM
    for j in 1:NUM
        N[i,j] = P[i,j]/sum(P, dims=2)[i]
    end
end

In [6]:
N

5×5 Matrix{Float64}:
 0.982054    0.00548355  0.00398804  0.00847458  0.0
 0.0433359   0.893875    0.057396    0.00539291  0.0
 0.00131279  0.0534789   0.755407    0.163822    0.0259794
 0.0         0.00381175  0.134479    0.633615    0.228095
 0.0         3.31686e-5  0.00202328  0.202295    0.795648

In [15]:
function nice_table(t_table, NUM)
    headers = []
    names = []
    for i in 1:NUM
        push!(headers, "Tier $i")
        push!(names, "Tier $i")
    end
    pretty_table(t_table, header = headers, row_names=names)
    return pretty_table(t_table, header = headers, row_names=names, backend=Val(:latex))
    
end

nice_table (generic function with 2 methods)

In [16]:
nice_table(N, NUM)

┌────────┬────────────┬────────────┬────────────┬────────────┬───────────┐
│        │     Tier 1 │     Tier 2 │     Tier 3 │     Tier 4 │    Tier 5 │
├────────┼────────────┼────────────┼────────────┼────────────┼───────────┤
│ Tier 1 │   0.982054 │ 0.00548355 │ 0.00398804 │ 0.00847458 │       0.0 │
│ Tier 2 │  0.0433359 │   0.893875 │   0.057396 │ 0.00539291 │       0.0 │
│ Tier 3 │ 0.00131279 │  0.0534789 │   0.755407 │   0.163822 │ 0.0259794 │
│ Tier 4 │        0.0 │ 0.00381175 │   0.134479 │   0.633615 │  0.228095 │
│ Tier 5 │        0.0 │ 3.31686e-5 │ 0.00202328 │   0.202295 │  0.795648 │
└────────┴────────────┴────────────┴────────────┴────────────┴───────────┘
\begin{tabular}{rrrrrr}
  \hline
   & \textbf{Tier 1} & \textbf{Tier 2} & \textbf{Tier 3} & \textbf{Tier 4} & \textbf{Tier 5} \\\hline
  Tier 1 & 0.982054 & 0.00548355 & 0.00398804 & 0.00847458 & 0.0 \\
  Tier 2 & 0.0433359 & 0.893875 & 0.057396 & 0.00539291 & 0.0 \\
  Tier 3 & 0.00131279 & 0.0534789 & 0.755407 & 0.163822 & 0.0259794 \\
  Tier 4 & 0.0 & 0.00381175 & 0.134479 & 0.633615 & 0.228095 \\
  Tier 5 & 0.0 & 3.31686e-5 & 0.00202328 & 0.202295 & 0.795648 \\\hline
\end{tabular}

In [22]:
using Pkg
Pkg.status("PrettyTables")

      Status `~/code/mapinator/estimation/Project.toml`
  [08abe8d2] PrettyTables v2.2.0

In [23]:
pretty_table(N)

┌────────────┬────────────┬────────────┬────────────┬───────────┐
│     Col. 1 │     Col. 2 │     Col. 3 │     Col. 4 │    Col. 5 │
├────────────┼────────────┼────────────┼────────────┼───────────┤
│   0.982054 │ 0.00548355 │ 0.00398804 │ 0.00847458 │       0.0 │
│  0.0433359 │   0.893875 │   0.057396 │ 0.00539291 │       0.0 │
│ 0.00131279 │  0.0534789 │   0.755407 │   0.163822 │ 0.0259794 │
│        0.0 │ 0.00381175 │   0.134479 │   0.633615 │  0.228095 │
│        0.0 │ 3.31686e-5 │ 0.00202328 │   0.202295 │  0.795648 │
└────────────┴────────────┴────────────┴────────────┴───────────┘