In [1]:
include("type_allocation_flexible.jl")

using Random, JSON

First we configure the settings:

In [2]:
Random.seed!(0)            # for reproducibility: ensures random results are the same on script restart
YEAR_INTERVAL = 2003:2025  # change this to select the years of data to include in the estimation
NUMBER_OF_TYPES = 4        # change this to select the number of types to classify academic departments into

4

We also need to collect the placements data. For this example we will be using the comprehensive API:

In [3]:
to_from_by_year_api = SBM_flexible.fetch_data("https://support.econjobmarket.org/api/placement_data")

DataStructures.DefaultDict{Any, Any, UnionAll} with 23 entries:
  "2003" => Dict{Any, Any}("17827"=>Dict{String, Any}("to_shortname"=>"Economic…
  "2005" => Dict{Any, Any}("11382"=>Dict{String, Any}("to_shortname"=>"Economic…
  "2014" => Dict{Any, Any}("56926"=>Dict{String, Any}("to_shortname"=>"Business…
  "2018" => Dict{Any, Any}("37159"=>Dict{String, Any}("to_shortname"=>"Dallas o…
  "2020" => Dict{Any, Any}("45907"=>Dict{String, Any}("to_shortname"=>"Economic…
  "2010" => Dict{Any, Any}("5422"=>Dict{String, Any}("to_shortname"=>"Managemen…
  "2016" => Dict{Any, Any}("1886"=>Dict{String, Any}("to_shortname"=>"Cons Fina…
  "2019" => Dict{Any, Any}("43054"=>Dict{String, Any}("to_shortname"=>"Computer…
  "2004" => Dict{Any, Any}("24943"=>Dict{String, Any}("to_shortname"=>"Economic…
  "2007" => Dict{Any, Any}("24350"=>Dict{String, Any}("to_shortname"=>"Economic…
  "2023" => Dict{Any, Any}("57428"=>Dict{String, Any}("to_shortname"=>"Health P…
  "2017" => Dict{Any, Any}("27626"=>Dict{String, Any}("to_shortname"=>"Economic…
  "2022" => Dict{Any, Any}("53030"=>Dict{String, Any}("to_shortname"=>"Economic…
  "2021" => Dict{Any, Any}("51250"=>Dict{String, Any}("to_shortname"=>"Fondazio…
  "2006" => Dict{Any, Any}("41645"=>Dict{String, Any}("to_shortname"=>"Fed Rese…
  "2011" => Dict{Any, Any}("9123"=>Dict{String, Any}("to_shortname"=>"Econ, Sto…
  "2025" => Dict{Any, Any}("56703"=>Dict{String, Any}("to_shortname"=>"Strategy…
  "2015" => Dict{Any, Any}("24377"=>Dict{String, Any}("to_shortname"=>"Economic…
  "2012" => Dict{Any, Any}("21569"=>Dict{String, Any}("to_shortname"=>"Economic…
  "2013" => Dict{Any, Any}("16501"=>Dict{String, Any}("to_shortname"=>"Finance,…
  "2024" => Dict{Any, Any}("57394"=>Dict{String, Any}("to_shortname"=>"Manageme…
  "2008" => Dict{Any, Any}("3720"=>Dict{String, Any}("to_shortname"=>"Economics…
  "2009" => Dict{Any, Any}("1886"=>Dict{String, Any}("to_shortname"=>"Economics…

Auto-recognition of API endpoints is provided assuming that the API URL is either `http` or `https` (and that the endpoint returns a raw list of placements with a `year` field). Otherwise, the endpoint is assumed to be a `json` file at the specified path.

Using the raw placements, we can sort them into academic and sink placements, as well as collect some labels:

In [4]:
academic, academic_to, academic_builder, rough_sink_builder, institution_mapping, reverse_mapping = SBM_flexible.get_builders(to_from_by_year_api, YEAR_INTERVAL);

We are mostly flexible in how we choose to design the set of sinks to include. One exception is teaching universities, which must always be included:

In [5]:
# sink of teaching universities that do not graduate PhDs
# this must be constructed using academic placements, not pre-defined sink placements

teaching_universities = Set() 
for dept_name in academic_to
    if !(dept_name in academic)
        # the department hired an assistant professor but never graduated anyone
        push!(teaching_universities, dept_name)
    end
end

The rest are built by standardized `if` statements:

In [6]:
public_sector = ("Public Sector", Set())
private_sector = ("Private Sector", Set())
other_groups = ("Other Groups", Set())

postdocs = ("Postdocs", Set())
lecturers = ("Lecturers", Set())
other_academic = ("Other Academic", Set())

for outcome in rough_sink_builder
    if outcome["recruiter_type"] == 5 # government institution
        push!(public_sector[2], (string(outcome["to_name"], " ($(public_sector[1]))"), outcome))
    elseif outcome["recruiter_type"] in [6, 7] # private sector: for and not for profit
        push!(private_sector[2], (string(outcome["to_name"], " ($(private_sector[1]))"), outcome))
    elseif outcome["recruiter_type"] == 8 # international organizations, think tanks, assorted
        push!(other_groups[2], (string(outcome["to_name"], " ($(other_groups[1]))"), outcome))

    # some other examples
    # every example here must also have a corresponding sink Set() above, 
    #     and an entry in sinks_to_include below
   
    elseif outcome["postype"] == 6
        # postdocs that are not in the above (i.e. academic; not public, private, or other)
        # please note that the included JSON does not contain postdocs; use the API
        push!(postdocs[2], (string(outcome["to_name"], " ($(postdocs[1]))"), outcome))
    elseif outcome["postype"] in [5, 7]
        # lecturers that are not in the above
        # please note that the included JSON does not contain lecturers; use the API
        push!(lecturers[2], (string(outcome["to_name"], " ($(lecturers[1]))"), outcome))
    else
        # everything else including terminal academic positions
        # this sink can only be constructed as an "else" statement
        push!(other_academic[2], (string(outcome["to_name"], " ($(other_academic[1]))"), outcome))
    
    end
end

# sort to ensure consistent ordering
academic_list = sort(collect(academic))
teaching_list = sort(collect(teaching_universities))
# to be consistent with the original estimation, we only include these additional sinks:
sinks_to_include = (public_sector, private_sector, other_groups)#, postdocs, lecturers, other_academic)

sink_builder, sinks, sink_labels = SBM_flexible.build_sinks(sinks_to_include, teaching_list)

NUMBER_OF_SINKS = length(sink_labels)
numtotal = NUMBER_OF_TYPES + NUMBER_OF_SINKS
institutions = vcat(academic_list, sinks...)
println("$(length(academic_list)) academic departments, $(length(institutions)) total departments")

Including the following sinks:
 Public Sector
 Private Sector
 Other Groups
 Teaching Universities
Total 4 sinks
870 academic departments, 2041 total departments

Next, the adjacency matrix:

In [7]:
length(academic_builder) + length(sink_builder)

12149

In [8]:
out = SBM_flexible.get_adjacency(academic_list, institutions, academic_builder, sink_builder);

Total 12149 Placements (found 12149 by sequence counting, 12149 by matrix sum)

In [9]:
sum(out)

12149

We are now ready to run the SBM itself:

In [10]:
@time est_obj, est_alloc = SBM_flexible.doit(out, length(academic_list), [length(s) for s in sinks], NUMBER_OF_TYPES, numtotal, 500 * (NUMBER_OF_TYPES-2) + 1000)

191.546873 seconds (389.54 k allocations: 20.313 MiB, 0.11% compilation time)

(35487.31919535547, Int32[4, 3, 2, 4, 4, 3, 4, 3, 4, 2  …  8, 8, 8, 8, 8, 8, 8, 8, 8, 8])

In [11]:
placement_rates, counts, sorted_allocation, full_likelihood = SBM_flexible.get_allocation(est_alloc, out, NUMBER_OF_TYPES, numtotal, institutions)

(Int32[1668 201 27 8; 1967 814 126 31; … ; 314 157 68 20; 827 681 259 135], Int32[2116 6900 11224 19780; 6900 22500 36600 64500; … ; 2116 6900 11224 19780; 32798 106950 173972 306590], Int32[4, 3, 2, 4, 4, 3, 4, 3, 4, 2  …  8, 8, 8, 8, 8, 8, 8, 8, 8, 8], -51068.7722563633)

We can explore the results:

In [12]:
placement_rates

8×4 Matrix{Int32}:
 1668  201   27    8
 1967  814  126   31
  681  431  229   32
   32   52   57   77
  987  427  130   50
 1154  356  111   40
  314  157   68   20
  827  681  259  135

In [13]:
placement_rates ./ counts # means

8×4 Matrix{Float64}:
 0.78828    0.0291304    0.00240556   0.000404449
 0.285072   0.0361778    0.00344262   0.00048062
 0.0606736  0.011776     0.00384641   0.000304994
 0.0016178  0.000806202  0.000543271  0.000416441
 0.125477   0.0166472    0.00311571   0.000679995
 0.104095   0.00984786   0.00188763   0.000385989
 0.148393   0.0227536    0.00605845   0.00101112
 0.025215   0.00636746   0.00148875   0.000440327

In [14]:
full_likelihood

-51068.7722563633

In [15]:
SBM_flexible.nice_table(placement_rates, NUMBER_OF_TYPES, NUMBER_OF_SINKS, sink_labels)

┌───────────────────────┬────────┬────────┬────────┬────────┬────────────┐
│                       │ Tier 1 │ Tier 2 │ Tier 3 │ Tier 4 │ Row Totals │
├───────────────────────┼────────┼────────┼────────┼────────┼────────────┤
│                Tier 1 │   1668 │    201 │     27 │      8 │       1904 │
│                Tier 2 │   1967 │    814 │    126 │     31 │       2938 │
│                Tier 3 │    681 │    431 │    229 │     32 │       1373 │
│                Tier 4 │     32 │     52 │     57 │     77 │        218 │
│         Public Sector │    987 │    427 │    130 │     50 │       1594 │
│        Private Sector │   1154 │    356 │    111 │     40 │       1661 │
│          Other Groups │    314 │    157 │     68 │     20 │        559 │
│ Teaching Universities │    827 │    681 │    259 │    135 │       1902 │
│         Column Totals │   7630 │   3119 │   1007 │    393 │      12149 │
└───────────────────────┴────────┴────────┴────────┴────────┴────────────┘
\begin{tabular}{rrrrrr}
  \hline
   & \textbf{Tier 1} & \textbf{Tier 2} & \textbf{Tier 3} & \textbf{Tier 4} & \textbf{Row Totals} \\\hline
  Tier 1 & 1668 & 201 & 27 & 8 & 1904 \\
  Tier 2 & 1967 & 814 & 126 & 31 & 2938 \\
  Tier 3 & 681 & 431 & 229 & 32 & 1373 \\
  Tier 4 & 32 & 52 & 57 & 77 & 218 \\
  Public Sector & 987 & 427 & 130 & 50 & 1594 \\
  Private Sector & 1154 & 356 & 111 & 40 & 1661 \\
  Other Groups & 314 & 157 & 68 & 20 & 559 \\
  Teaching Universities & 827 & 681 & 259 & 135 & 1902 \\
  Column Totals & 7630 & 3119 & 1007 & 393 & 12149 \\\hline
\end{tabular}

To save the allocation to file, if we want to explore it later, we can do the following:

In [16]:
type_dictionary = []
for (i, alloc) in enumerate(sorted_allocation)
    if alloc in 1:NUMBER_OF_TYPES
        inst_id = reverse_mapping[institutions[i]]
        push!(type_dictionary, Dict("name" => institutions[i], "institution_id" => inst_id, "type" => alloc))
    end
end

In [17]:
open(".estimates/id_to_type_api.json", "w") do f
    write(f, JSON.json(type_dictionary))
end;

The allocation itself:

In [18]:
for sorted_type in 1:NUMBER_OF_TYPES
    counter = 0
    inst_hold = []
    println("TYPE $sorted_type:")
    for (i, sbm_type) in enumerate(sorted_allocation)
        if sbm_type == sorted_type
            push!(inst_hold, institutions[i])
            counter += 1
        end
    end
    for inst in sort(inst_hold)
        println("  ", inst)
    end
    println("Total Institutions: $counter")
    println()
end

TYPE 1:
  Bocconi University
  Boston College
  Boston University
  Brown University
  Carnegie Mellon University
  Columbia University
  Cornell University
  Duke University
  Harvard University
  Johns Hopkins University
  London School of Economics and Political Science
  Massachusetts Institute of Technology
  Michigan State University
  New York University
  Northwestern University
  Ohio State University
  Pennsylvania State University
  Princeton University
  Purdue University
  Stanford University
  Texas A&M University, College Station
  Tilburg University
  University College London
  University of British Columbia
  University of California Los Angeles (UCLA)
  University of California, Berkeley
  University of California, Davis
  University of Chicago
  University of Illinois at Urbana-Champaign
  University of Mannheim
  University of Maryland
  University of Michigan
  University of Minnesota, Twin Cities
  University of Oxford
  University of Pennsylvania
  University of Rochester
  University of Southern California
  University of Texas at Austin
  University of Toronto
  University of Virginia
  University of Washington
  University of Wisconsin, Madison
  Université Toulouse Capitole
  Vanderbilt University
  Washington University in St. Louis
  Yale University
Total Institutions: 46

TYPE 2:
  Aarhus University
  American University
  Arizona State University
  Auburn University
  Australian National University
  BI Norwegian Business School
  Baruch College, City University of New York
  Binghamton University (SUNY)
  CEMFI
  California Institute of Technology (Caltech)
  Central University of Finance and Economics
  Chinese University of Hong Kong
  City University of Hong Kong
  City University of London
  Clemson University
  Concordia University
  Copenhagen Business School
  ETH Zurich
  Emory University
  Erasmus University Rotterdam
  European University Institute
  Florida International University
  Florida State University
  Fudan University
  George Mason University
  George Washington University
  Georgetown University
  Georgia Institute of Technology
  Georgia State University
  Goethe-Universität Frankfurt am Main
  HEC Paris
  Hong Kong Baptist University
  Hong Kong University of Science and Technology
  INSEAD
  Imperial College London
  Indiana University Bloomington
  Instituto Tecnologico Autónomo de Mexico (ITAM)
  Iowa State University
  Jinan University
  Kansas State University
  Katholieke Universiteit Leuven
  London Business School
  Louisiana State University
  Ludwig-Maximilians-Universitat München (LMU) (University of Munich)
  Lund University
  Maastricht University
  McGill University
  McMaster University
  Miami University
  Monash University
  Nanyang Technological University
  National Taiwan University
  National University of Singapore
  New Economic School
  North Carolina State University
  Northeastern University
  Norwegian School of Economics (NHH)
  Oklahoma State University
  Oregon State University
  Peking University
  Queen Mary University of London
  Queen's University
  Rice University
  Rutgers, The State University of New Jersey
  Sciences Po
  Shanghai University of Finance and Economics
  Simon Fraser University
  Singapore Management University
  Southern Methodist University
  Southwestern University of Finance and Economics
  Stockholm School of Economics
  Stockholm University
  Stony Brook University (SUNY)
  Syracuse University
  Temple University
  Texas Tech University
  The New School
  Toronto Metropolitan University
  Tsinghua University
  Tulane University
  Universidad Carlos III de Madrid
  Universidad de Navarra
  Universidad de los Andes
  Universitat Autònoma de Barcelona
  Universitat Pompeu Fabra
  University of Alabama
  University of Alberta
  University of Amsterdam
  University of Arizona
  University of Bonn
  University of Bristol
  University of Calgary
  University of California, Irvine
  University of California, Riverside
  University of California, San Diego
  University of California, Santa Barbara
  University of California, Santa Cruz
  University of Cambridge
  University of Colorado, Boulder
  University of Connecticut
  University of Copenhagen
  University of Delaware
  University of Essex
  University of Florida
  University of Georgia
  University of Glasgow
  University of Gothenburg
  University of Groningen
  University of Hawaiʻi at Mānoa
  University of Hong Kong
  University of Houston
  University of Illinois at Chicago
  University of International Business and Economics
  University of Iowa
  University of Kansas
  University of Kentucky
  University of Lausanne
  University of Manchester
  University of Massachusetts, Amherst
  University of Melbourne
  University of Missouri, Columbia
  University of Nebraska, Lincoln
  University of New South Wales (UNSW), Sydney
  University of North Carolina, Chapel Hill
  University of Notre Dame
  University of Nottingham
  University of Oklahoma
  University of Oregon
  University of Pittsburgh
  University of South Carolina
  University of Sydney
  University of Tennessee, Knoxville
  University of Texas at Dallas
  University of Utah
  University of Vienna
  University of Warwick
  University of Zurich
  Università di Bologna
  Università di Roma Tor Vergata
  Université Catholique de Louvain
  Universíté de Montréal
  Uppsala University
  Virginia Tech
  Vrije Universiteit Amsterdam
  Washington State University
  West Virginia University
  Western University
  Wuhan University
  Xiamen University
  École d'Économie de Paris
Total Institutions: 150

TYPE 3:
  Aalto University
  Aix-Marseille Université
  Aligarh Muslim University
  Ball State University
  Barcelona School of Economics
  Bentley University
  Bilkent University
  Birkbeck College, University of London
  Boğaziçi University
  Brandeis University
  CERGE-EI (Center for Economic Research and Graduate Education – Economics Institute)
  COMSATS University Islamabad
  Ca' Foscari University Venice
  Cairo University
  California State Polytechnic University, Pomona
  Cardiff University
  Carleton University
  Center for Research in Economics and Statistics (CREST)
  Central European University
  Central Michigan University
  Charles University
  Chr. Michelsen Institute (CMI)
  Chung-Ang University
  City University of New York Graduate Center
  Claremont Graduate University
  Clark University
  Collegio Carlo Alberto
  Colorado School of Mines
  Colorado State University
  Dalhousie University
  Deakin University
  Delft University of Technology
  Dongbei University of Finance and Economics
  Drexel University
  Durham University
  ESCP Business School
  ESMT Berlin
  ESSEC Business School
  East Carolina University
  East China Normal University
  Eastern Kentucky University
  Eastern Mediterranean University
  Ecole Polytechnique (IP Paris)
  Emlyon Business School
  Florida Atlantic University
  Fordham University
  Frankfurt School of Finance & Management
  Freie Universität Berlin
  Fundação Getulio Vargas (FGV)
  Ghent University
  Graduate Institute of International and Development Studies
  Grenoble Ecole de Management
  Hanyang University
  Hebrew University of Jerusalem
  Heidelberg University
  Hong Kong Polytechnic University
  Howard University
  Humboldt University Berlin
  Hunter College, CUNY
  IE University
  IMT School for Advanced Studies Lucca
  Indian Institute of Management Ahmedabad
  Indian Institute of Management Bangalore
  Indian Institute of Management Indore
  Indian Institute of Technology, Kanpur
  Indian Statistical Institute, Delhi
  Indiana University Purdue University Indianapolis (IUPUI)
  Indira Gandhi Institute of Development Research (IGIDR)
  Insper (Institute of Education and Research)
  Jawaharlal Nehru University
  Johannes Kepler University Linz
  King's College London
  Korea University
  Koç University
  LUISS Guido Carli
  Lancaster University
  Lehigh University
  Leiden University
  Libera Università di Bolzano
  Loughborough University
  Manchester Metropolitan University
  Middle East Technical University
  Middle Tennessee State University
  Mississippi State University
  National Central University
  National Graduate Institute for Policy Studies (GRIPS), Japan
  National Research University Higher School of Economics, Moscow
  National Research University Higher School of Economics, St. Petersburg
  National University of Computer & Emerging Sciences
  New Mexico State University
  New York University Abu Dhabi
  New York University Shanghai
  Northern Illinois University
  Osaka University
  Pardee RAND Graduate School
  Pontifical Catholic University of Rio de Janeiro
  Pontificia Universidad Católica de Chile
  Queens' University Belfast
  Queensland University of Technology
  Radboud University
  Rensselaer Polytechnic Institute
  Royal Holloway, University of London
  Rutgers University, Newark
  SKEMA Business School
  SUNY Buffalo State
  Sabancı University
  Sam Houston State University
  Sapienza Università di Roma
  Sciences Po Toulouse
  Seoul National University
  Shandong University
  Shiv Nadar University
  Sogang University
  Southern Illinois University, Carbondale
  State University of New York at Buffalo
  Stevens Institute of Technology
  Suffolk University
  Sun Yat-Sen University
  Technische Universität Berlin
  Tecnológico de Monterrey
  Tel Aviv University
  Texas A&M International University
  Towson University
  Trinity College Dublin, University of Dublin
  Tufts University
  Union College
  Universidad Adolfo Ibáñez
  Universidad Complutense de Madrid
  Universidad Publica de Navarra
  Universidad de Alicante
  Universidad de Chile
  Universidad del Rosario
  Universidade Nova de Lisboa
  Universitat Ramon Llull
  Universitat de Barcelona
  Universitat de València
  Universiti Utara Malaysia
  University College Dublin
  University at Albany (SUNY)
  University of Adelaide
  University of Alabama at Birmingham
  University of Arkansas
  University of Auckland
  University of Bath
  University of Bern
  University of Birmingham
  University of Cape Town
  University of Central Florida
  University of Cincinnati
  University of Cologne
  University of Colorado, Denver
  University of East Anglia
  University of Edinburgh
  University of Exeter
  University of Guelph
  University of Haifa
  University of Helsinki
  University of Innsbruck
  University of Jena
  University of Kent
  University of Konstanz
  University of Leeds
  University of Leicester
  University of Liverpool
  University of Louisville
  University of Luxembourg
  University of Macau
  University of Maine, Orono
  University of Manitoba
  University of Massachusetts, Boston
  University of Memphis
  University of Miami
  University of Mississippi
  University of Namur
  University of Nevada, Las Vegas (UNLV)
  University of Nevada, Reno
  University of New Hampshire
  University of New Mexico
  University of North Carolina, Charlotte
  University of North Carolina, Greensboro
  University of North Texas
  University of Oslo
  University of Ottawa
  University of Queensland
  University of Reading
  University of Rhode Island
  University of Saskatchewan
  University of Sheffield
  University of South Alabama
  University of South Florida
  University of Southampton
  University of Southern Denmark
  University of St Andrews
  University of St. Gallen
  University of Stavanger
  University of Strathclyde
  University of Surrey
  University of Sussex
  University of São Paulo
  University of Technology Sydney
  University of Tehran
  University of Texas at Arlington
  University of Texas at El Paso
  University of Texas at San Antonio
  University of Tokyo
  University of Tsukuba
  University of Vaasa
  University of Victoria
  University of Waterloo
  University of Western Australia
  University of Wisconsin, Milwaukee
  University of Wyoming
  University of York
  Università Cattolica del Sacro Cuore
  Università Degli Studi di Milano
  Università degli Studi di Firenze
  Università degli Studi di Pavia
  Università degli Studi di Torino
  Università degli Studi di Trento
  Università degli Studi di Verona
  Università della Svizzera Italiana
  Université Clermont Auvergne
  Université Laval
  Université Libre de Bruxelles
  Université Paris 1 Panthéon-Sorbonne
  Université Paris-Dauphine
  Université Paris-Est Créteil
  Université de Genève
  Université du Québec à Montréal (UQAM)
  Utah State University
  Utrecht University
  Victoria University of Wellington
  Vienna Graduate School of Finance (VGSF)
  Vienna University of Economics and Business
  Wageningen University
  Waseda University
  Wayne State University
  Wilfrid Laurier University
  York University
  Zhejiang University
  Zhongnan University of Economics and Law
  École Polytechnique Fédérale de Lausanne
  Özyeğin University
  İzmir University of Economics
Total Institutions: 244

TYPE 4:
  Aalborg University
  Academy of Postgraduate Education (Академия последипломного образования)
  AgroParisTech
  Alexandria University
  Allameh Tabataba'i University
  Amity University
  Anadolu University
  Anglia Ruskin University
  Aristotle University of Thessaloniki
  Aston University
  Athens University of Economics and Business
  Auckland University of Technology
  Aveiro University
  Babcock University
  Banco de Portugal
  Bank of Finland
  Bayero University, Kano
  Beijing Institute of Technology
  Bharathiar University
  Bharathidasan University
  Bielefeld University
  Bond University
  Bournemouth University
  Brunel University London
  Brussels Free University
  Bucharest Academy of Economic Studies
  Budapest University of Technology and Economics
  CY Cergy Paris Université
  Carl von Ossietzky Universität Oldenburg
  Chaoyang University of Technology
  Chaudhary Charan Singh University
  Chinese Academy of Sciences
  Cochin University of Science and Technology
  Constructor University
  Corvinus University of Budapest
  Covenant University
  Coventry University
  Cranfield University
  Curtin University
  Dalian University of Technology
  De Montfort University
  Devi Ahilya Vishwavidyalaya, Indore
  Drew University
  Dublin City University
  Dublin Institute of Technology
  EDHEC Business School
  ENSAE Paris Tech
  Ecole des Hautes Etudes en Sciences Sociales (EHESS)
  Edith Cowan University
  Ege University
  Eindhoven University of Technology
  FUCAPE Business School
  Federal Reserve Bank of New York
  Federal University of Paraná
  Federal University of Rio de Janeiro
  Federal University of Technology Akure
  Ferdowsi University of Mashhad
  Friedrich-Alexander-Universität Erlangen-Nürnberg
  Galatasaray University
  Gauhati University
  Glasgow Caledonian University
  Gomal University
  Gran Sasso Science Institute
  Griffith University
  Guangxi University
  Halle Institute for Economic Research (IWH)
  Hamburg University
  Hanken School of Economics
  Haramaya University
  Harbin Institute of Technology
  Heinrich Heine University Dusseldorf
  Helwan University
  Heriot Watt University
  Hohai University
  ICFAI Foundation for Higher Education
  ISM University of Management and Economics
  ITMO University
  Illinois Institute of Technology
  Indian Institute of Foreign Trade
  Indian Institute of Management Kozhikode
  Indian Institute of Science
  Indian Institute of Technology, Bombay
  Indian Institute of Technology, Delhi
  Indian Institute of Technology, Indore
  Indian Institute of Technology, Kharagpur
  Indian Institute of Technology, Madras
  Indian Institute of Technology, Roorkee
  Indian Statistical Institute, Kolkata
  Indiana Institute of Technology
  Indira Gandhi University, Meerpur, Rewari
  Inner Mongolia Agriculture Univeristy
  Institut Agro Montpellier
  Institut national de recherche pour l'agriculture, l'alimentation et l'environnement (INRAE)
  Institute for Advanced Study in Toulouse
  Institute of Technology Sligo
  Instituto Politécnico Nacional (IPN)
  Instituto Universitário de Lisboa, ISCTE-IUL
  Instituto de Matemática Pura e Aplicada (IMPA)
  International Centre for Education in Islamic Finance
  International Islamic University Malaysia
  International Islamic University, Islamabad
  International Monetary Fund (IMF)
  International Trade Centre
  Iran University of Science and Tchnology
  Islamic Science University of Malaysia
  Istanbul Bilgi University
  Istanbul University
  Jadavpur University
  Jaypee Institute of Information Technology
  Jilin University
  Jiwaji University
  Johannes Gutenberg-University Mainz
  Julius-Maximilians-Universität Würzburg
  Justus-Liebig-Universität Gießen
  Jönköping University
  K. N. Toosi University of Technology
  KTH Royal Institute of Technology
  Kangwon National University
  Karamanoğlu Mehmetbey Üniversitesi
  Katholische Universität Eichstätt-Ingolstadt
  Kiel Institute for the World Economy
  Kiel University
  Kingston University London
  Kobe University
  Korea Advanced Institute of Science and Technology (KAIST)
  Kurukshetra University
  Kwara State University
  Kyoto University
  Lahore School of Economics
  Leibniz Universität Hannover
  Leipzig University
  Limkokwing University
  Linköping University
  Linnéuniversitetets
  Lomonosov Moscow State University (Московский государственный университет имени М. В. Ломоносова)
  Luleå University of Technology
  MINES ParisTech
  Macquarie University
  Maharshi Dayanand Saraswati University, Ajmer
  Manchester University
  Marietta College
  Marmara University
  Martin Luther University of Halle-Wittenberg
  Massey University
  Maulana Azad National Institute of Technology Bhopal (MANIT)
  Meiji University
  Mewar University
  Middle East Technical University - Northern Cyprus Campus
  Multimedia University
  Nanjing University of Aeronautics and Astronautics
  National Institute of Development Administration
  National Institute of Technology Jalandhar
  National University of Sciences and Technology (NUST)
  Near East University
  Nelson Mandela University
  Newcastle University
  Nnamdi Azikiwe University
  Norges Artiske Universitet
  North-West University
  Norwegian University of Life Sciences
  Norwegian University of Science and Technology
  Nottingham Trent University
  Obafemi Awolowo University
  Old Dominion University
  Otto-von-Guericke University Magdeburg
  Oxford Brookes University
  Paderborn University
  Pan-Atlantic University
  Penn State Abington
  Philipps University Marburg
  Politecnico di Torino
  Poznań University of Economics and Business
  Punjabi University Patiala
  Pusan National University
  Quaid-i-Azam University
  RAND Corporation
  RWTH Aachen University
  Rabindra Bharati University
  Recinto Universitario de Mayagüez, University of Puerto Rico
  Ritsumeikan Asia Pacific University
  Royal Melbourne Institute of Technology (RMIT)
  Ruhr Graduate School in Economics
  Ruhr University Bochum
  SOAS (School of Oriental and African Studies), University of London
  SWPS University of Social Sciences and Humanities
  Saint Mary's University (SMU)
  Saint Petersburg University
  Sant'Anna School of Advanced Studies
  Sari Agricultural Sciences and Natural Resources University
  Savitribai Phule Pune University
  Scuola Normale Superiore
  Sharif University of Technology
  Sikkim University
  Sorbonne Université
  South Asian University
  Southern Illinois University
  Ss. Cyril and Methodius University in Skopje (Универзитет „Св. Кирил и Методиј“ во Скопје)
  St. Petersburg State University of Economics
  St. Thomas University
  Staffordshire University
  Stellenbosch University
  Stripe
  Sultan Qaboos University
  Swedish University of Agricultural Sciences
  Swiss Tropical and Public Health Institute
  Symbiosis International (Deemed University)
  Tallinn University of Technology
  Tampere University
  Tarbiat Modares University
  Taylor's University
  Technical University of Crete